// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/sensor/v1/sensor.proto

package sensorv1

import (
	v1 "github.com/sysarmor/sysarmor-next-project/api/proto/event/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawProcess struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Pid                uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid               uint32                 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Binary             string                 `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`
	Argv               []string               `protobuf:"bytes,4,rep,name=argv,proto3" json:"argv,omitempty"`
	Uid                uint32                 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	StartTimeNs        uint64                 `protobuf:"varint,6,opt,name=start_time_ns,json=startTimeNs,proto3" json:"start_time_ns,omitempty"`
	Cgroup             string                 `protobuf:"bytes,7,opt,name=cgroup,proto3" json:"cgroup,omitempty"`
	SensorExecId       string                 `protobuf:"bytes,8,opt,name=sensor_exec_id,json=sensorExecId,proto3" json:"sensor_exec_id,omitempty"`
	SensorParentExecId string                 `protobuf:"bytes,9,opt,name=sensor_parent_exec_id,json=sensorParentExecId,proto3" json:"sensor_parent_exec_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RawProcess) Reset() {
	*x = RawProcess{}
	mi := &file_api_proto_sensor_v1_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawProcess) ProtoMessage() {}

func (x *RawProcess) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_v1_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawProcess.ProtoReflect.Descriptor instead.
func (*RawProcess) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_v1_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *RawProcess) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RawProcess) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *RawProcess) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *RawProcess) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *RawProcess) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RawProcess) GetStartTimeNs() uint64 {
	if x != nil {
		return x.StartTimeNs
	}
	return 0
}

func (x *RawProcess) GetCgroup() string {
	if x != nil {
		return x.Cgroup
	}
	return ""
}

func (x *RawProcess) GetSensorExecId() string {
	if x != nil {
		return x.SensorExecId
	}
	return ""
}

func (x *RawProcess) GetSensorParentExecId() string {
	if x != nil {
		return x.SensorParentExecId
	}
	return ""
}

type RawObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Dst           string                 `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	TargetPid     uint32                 `protobuf:"varint,3,opt,name=target_pid,json=targetPid,proto3" json:"target_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawObject) Reset() {
	*x = RawObject{}
	mi := &file_api_proto_sensor_v1_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawObject) ProtoMessage() {}

func (x *RawObject) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_v1_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawObject.ProtoReflect.Descriptor instead.
func (*RawObject) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_v1_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *RawObject) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RawObject) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *RawObject) GetTargetPid() uint32 {
	if x != nil {
		return x.TargetPid
	}
	return 0
}

type SensorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonoNs        uint64                 `protobuf:"varint,1,opt,name=mono_ns,json=monoNs,proto3" json:"mono_ns,omitempty"`
	Kind          v1.EventKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=sysarmor.event.v1.EventKind" json:"kind,omitempty"`
	Proc          *RawProcess            `protobuf:"bytes,3,opt,name=proc,proto3" json:"proc,omitempty"`
	Object        *RawObject             `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	ContainerId   string                 `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	RawRef        string                 `protobuf:"bytes,6,opt,name=raw_ref,json=rawRef,proto3" json:"raw_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorEvent) Reset() {
	*x = SensorEvent{}
	mi := &file_api_proto_sensor_v1_sensor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorEvent) ProtoMessage() {}

func (x *SensorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_v1_sensor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorEvent.ProtoReflect.Descriptor instead.
func (*SensorEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_v1_sensor_proto_rawDescGZIP(), []int{2}
}

func (x *SensorEvent) GetMonoNs() uint64 {
	if x != nil {
		return x.MonoNs
	}
	return 0
}

func (x *SensorEvent) GetKind() v1.EventKind {
	if x != nil {
		return x.Kind
	}
	return v1.EventKind(0)
}

func (x *SensorEvent) GetProc() *RawProcess {
	if x != nil {
		return x.Proc
	}
	return nil
}

func (x *SensorEvent) GetObject() *RawObject {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *SensorEvent) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *SensorEvent) GetRawRef() string {
	if x != nil {
		return x.RawRef
	}
	return ""
}

type SensorHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroppedEvents uint64                 `protobuf:"varint,1,opt,name=dropped_events,json=droppedEvents,proto3" json:"dropped_events,omitempty"`
	EventsPerSec  float64                `protobuf:"fixed64,2,opt,name=events_per_sec,json=eventsPerSec,proto3" json:"events_per_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorHealth) Reset() {
	*x = SensorHealth{}
	mi := &file_api_proto_sensor_v1_sensor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorHealth) ProtoMessage() {}

func (x *SensorHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sensor_v1_sensor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorHealth.ProtoReflect.Descriptor instead.
func (*SensorHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_sensor_v1_sensor_proto_rawDescGZIP(), []int{3}
}

func (x *SensorHealth) GetDroppedEvents() uint64 {
	if x != nil {
		return x.DroppedEvents
	}
	return 0
}

func (x *SensorHealth) GetEventsPerSec() float64 {
	if x != nil {
		return x.EventsPerSec
	}
	return 0
}

var File_api_proto_sensor_v1_sensor_proto protoreflect.FileDescriptor

const file_api_proto_sensor_v1_sensor_proto_rawDesc = "" +
	"\n" +
	" api/proto/sensor/v1/sensor.proto\x12\x12sysarmor.sensor.v1\x1a\x1eapi/proto/event/v1/event.proto\"\x85\x02\n" +
	"\n" +
	"RawProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\rR\x04ppid\x12\x16\n" +
	"\x06binary\x18\x03 \x01(\tR\x06binary\x12\x12\n" +
	"\x04argv\x18\x04 \x03(\tR\x04argv\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\rR\x03uid\x12\"\n" +
	"\rstart_time_ns\x18\x06 \x01(\x04R\vstartTimeNs\x12\x16\n" +
	"\x06cgroup\x18\a \x01(\tR\x06cgroup\x12$\n" +
	"\x0esensor_exec_id\x18\b \x01(\tR\fsensorExecId\x121\n" +
	"\x15sensor_parent_exec_id\x18\t \x01(\tR\x12sensorParentExecId\"P\n" +
	"\tRawObject\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\tR\x03dst\x12\x1d\n" +
	"\n" +
	"target_pid\x18\x03 \x01(\rR\ttargetPid\"\xff\x01\n" +
	"\vSensorEvent\x12\x17\n" +
	"\amono_ns\x18\x01 \x01(\x04R\x06monoNs\x120\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1c.sysarmor.event.v1.EventKindR\x04kind\x122\n" +
	"\x04proc\x18\x03 \x01(\v2\x1e.sysarmor.sensor.v1.RawProcessR\x04proc\x125\n" +
	"\x06object\x18\x04 \x01(\v2\x1d.sysarmor.sensor.v1.RawObjectR\x06object\x12!\n" +
	"\fcontainer_id\x18\x05 \x01(\tR\vcontainerId\x12\x17\n" +
	"\araw_ref\x18\x06 \x01(\tR\x06rawRef\"[\n" +
	"\fSensorHealth\x12%\n" +
	"\x0edropped_events\x18\x01 \x01(\x04R\rdroppedEvents\x12$\n" +
	"\x0eevents_per_sec\x18\x02 \x01(\x01R\feventsPerSecBHZFgithub.com/sysarmor/sysarmor-next-project/api/proto/sensor/v1;sensorv1b\x06proto3"

var (
	file_api_proto_sensor_v1_sensor_proto_rawDescOnce sync.Once
	file_api_proto_sensor_v1_sensor_proto_rawDescData []byte
)

func file_api_proto_sensor_v1_sensor_proto_rawDescGZIP() []byte {
	file_api_proto_sensor_v1_sensor_proto_rawDescOnce.Do(func() {
		file_api_proto_sensor_v1_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sensor_v1_sensor_proto_rawDesc), len(file_api_proto_sensor_v1_sensor_proto_rawDesc)))
	})
	return file_api_proto_sensor_v1_sensor_proto_rawDescData
}

var file_api_proto_sensor_v1_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_sensor_v1_sensor_proto_goTypes = []any{
	(*RawProcess)(nil),   // 0: sysarmor.sensor.v1.RawProcess
	(*RawObject)(nil),    // 1: sysarmor.sensor.v1.RawObject
	(*SensorEvent)(nil),  // 2: sysarmor.sensor.v1.SensorEvent
	(*SensorHealth)(nil), // 3: sysarmor.sensor.v1.SensorHealth
	(v1.EventKind)(0),    // 4: sysarmor.event.v1.EventKind
}
var file_api_proto_sensor_v1_sensor_proto_depIdxs = []int32{
	4, // 0: sysarmor.sensor.v1.SensorEvent.kind:type_name -> sysarmor.event.v1.EventKind
	0, // 1: sysarmor.sensor.v1.SensorEvent.proc:type_name -> sysarmor.sensor.v1.RawProcess
	1, // 2: sysarmor.sensor.v1.SensorEvent.object:type_name -> sysarmor.sensor.v1.RawObject
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_sensor_v1_sensor_proto_init() }
func file_api_proto_sensor_v1_sensor_proto_init() {
	if File_api_proto_sensor_v1_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sensor_v1_sensor_proto_rawDesc), len(file_api_proto_sensor_v1_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_sensor_v1_sensor_proto_goTypes,
		DependencyIndexes: file_api_proto_sensor_v1_sensor_proto_depIdxs,
		MessageInfos:      file_api_proto_sensor_v1_sensor_proto_msgTypes,
	}.Build()
	File_api_proto_sensor_v1_sensor_proto = out.File
	file_api_proto_sensor_v1_sensor_proto_goTypes = nil
	file_api_proto_sensor_v1_sensor_proto_depIdxs = nil
}
