// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: api/proto/analytics/v1/agentgateway.proto

package analyticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGateway_Upload_FullMethodName = "/sysarmor.analytics.v1.AgentGateway/Upload"
	AgentGateway_Stream_FullMethodName = "/sysarmor.analytics.v1.AgentGateway/Stream"
)

// AgentGatewayClient is the client API for AgentGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentGatewayClient interface {
	Upload(ctx context.Context, in *UploadBatch, opts ...grpc.CallOption) (*UploadAck, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, StreamFrame], error)
}

type agentgatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGatewayClient(cc grpc.ClientConnInterface) AgentGatewayClient {
	return &agentgatewayClient{cc}
}

func (c *agentgatewayClient) Upload(ctx context.Context, in *UploadBatch, opts ...grpc.CallOption) (*UploadAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAck)
	err := c.cc.Invoke(ctx, AgentGateway_Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentgatewayClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, StreamFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[0], AgentGateway_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFrame, StreamFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_StreamClient = grpc.BidiStreamingClient[StreamFrame, StreamFrame]

// AgentGatewayServer is the server API for AgentGateway service.
// All implementations must embed UnimplementedAgentGatewayServer
// for forward compatibility.
type AgentGatewayServer interface {
	Upload(context.Context, *UploadBatch) (*UploadAck, error)
	Stream(grpc.BidiStreamingServer[StreamFrame, StreamFrame]) error
	mustEmbedUnimplementedAgentGatewayServer()
}

// UnimplementedAgentGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGatewayServer struct{}

func (UnimplementedAgentGatewayServer) Upload(context.Context, *UploadBatch) (*UploadAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedAgentGatewayServer) Stream(grpc.BidiStreamingServer[StreamFrame, StreamFrame]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedAgentGatewayServer) mustEmbedUnimplementedAgentGatewayServer() {}
func (UnimplementedAgentGatewayServer) testEmbeddedByValue()                      {}

// UnsafeAgentGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGatewayServer will
// result in compilation errors.
type UnsafeAgentGatewayServer interface {
	mustEmbedUnimplementedAgentGatewayServer()
}

func RegisterAgentGatewayServer(s grpc.ServiceRegistrar, srv AgentGatewayServer) {
	// If the following call panics, it indicates UnimplementedAgentGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGateway_ServiceDesc, srv)
}

func _AgentGateway_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).Upload(ctx, req.(*UploadBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServer).Stream(&grpc.GenericServerStream[StreamFrame, StreamFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_StreamServer = grpc.BidiStreamingServer[StreamFrame, StreamFrame]

// AgentGateway_ServiceDesc is the grpc.ServiceDesc for AgentGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysarmor.analytics.v1.AgentGateway",
	HandlerType: (*AgentGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _AgentGateway_Upload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _AgentGateway_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/analytics/v1/agentgateway.proto",
}
