// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: api/proto/analytics/v1/agentdata.proto

package analyticsv1

import (
	context "context"
	v1 "github.com/sysarmor/sysarmor-next-project/api/proto/dataplane/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentDataService_Upload_FullMethodName = "/sysarmor.analytics.v1.AgentDataService/Upload"
)

// AgentDataServiceClient is the client API for AgentDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentDataServiceClient interface {
	Upload(ctx context.Context, in *v1.DataBatch, opts ...grpc.CallOption) (*v1.DataAck, error)
}

type agentDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentDataServiceClient(cc grpc.ClientConnInterface) AgentDataServiceClient {
	return &agentDataServiceClient{cc}
}

func (c *agentDataServiceClient) Upload(ctx context.Context, in *v1.DataBatch, opts ...grpc.CallOption) (*v1.DataAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DataAck)
	err := c.cc.Invoke(ctx, AgentDataService_Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentDataServiceServer is the server API for AgentDataService service.
// All implementations must embed UnimplementedAgentDataServiceServer
// for forward compatibility.
type AgentDataServiceServer interface {
	Upload(context.Context, *v1.DataBatch) (*v1.DataAck, error)
	mustEmbedUnimplementedAgentDataServiceServer()
}

// UnimplementedAgentDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentDataServiceServer struct{}

func (UnimplementedAgentDataServiceServer) Upload(context.Context, *v1.DataBatch) (*v1.DataAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedAgentDataServiceServer) mustEmbedUnimplementedAgentDataServiceServer() {}
func (UnimplementedAgentDataServiceServer) testEmbeddedByValue()                          {}

// UnsafeAgentDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentDataServiceServer will
// result in compilation errors.
type UnsafeAgentDataServiceServer interface {
	mustEmbedUnimplementedAgentDataServiceServer()
}

func RegisterAgentDataServiceServer(s grpc.ServiceRegistrar, srv AgentDataServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentDataService_ServiceDesc, srv)
}

func _AgentDataService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DataBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentDataServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentDataService_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentDataServiceServer).Upload(ctx, req.(*v1.DataBatch))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentDataService_ServiceDesc is the grpc.ServiceDesc for AgentDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysarmor.analytics.v1.AgentDataService",
	HandlerType: (*AgentDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _AgentDataService_Upload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/analytics/v1/agentdata.proto",
}
