// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/analytics/v1/agentdata.proto

package analyticsv1

import (
	v1 "github.com/sysarmor/sysarmor-next-project/api/proto/dataplane/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_analytics_v1_agentdata_proto protoreflect.FileDescriptor

const file_api_proto_analytics_v1_agentdata_proto_rawDesc = "" +
	"\n" +
	"&api/proto/analytics/v1/agentdata.proto\x12\x15sysarmor.analytics.v1\x1a&api/proto/dataplane/v1/dataplane.proto2^\n" +
	"\x10AgentDataService\x12J\n" +
	"\x06Upload\x12 .sysarmor.dataplane.v1.DataBatch\x1a\x1e.sysarmor.dataplane.v1.DataAckBNZLgithub.com/sysarmor/sysarmor-next-project/api/proto/analytics/v1;analyticsv1b\x06proto3"

var file_api_proto_analytics_v1_agentdata_proto_goTypes = []any{
	(*v1.DataBatch)(nil), // 0: sysarmor.dataplane.v1.DataBatch
	(*v1.DataAck)(nil),   // 1: sysarmor.dataplane.v1.DataAck
}
var file_api_proto_analytics_v1_agentdata_proto_depIdxs = []int32{
	0, // 0: sysarmor.analytics.v1.AgentDataService.Upload:input_type -> sysarmor.dataplane.v1.DataBatch
	1, // 1: sysarmor.analytics.v1.AgentDataService.Upload:output_type -> sysarmor.dataplane.v1.DataAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_analytics_v1_agentdata_proto_init() }
func file_api_proto_analytics_v1_agentdata_proto_init() {
	if File_api_proto_analytics_v1_agentdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_analytics_v1_agentdata_proto_rawDesc), len(file_api_proto_analytics_v1_agentdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_analytics_v1_agentdata_proto_goTypes,
		DependencyIndexes: file_api_proto_analytics_v1_agentdata_proto_depIdxs,
	}.Build()
	File_api_proto_analytics_v1_agentdata_proto = out.File
	file_api_proto_analytics_v1_agentdata_proto_goTypes = nil
	file_api_proto_analytics_v1_agentdata_proto_depIdxs = nil
}
