// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: api/proto/analytics/v1/link1.proto

package analyticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Link1_Upload_FullMethodName = "/sysarmor.analytics.v1.Link1/Upload"
	Link1_Stream_FullMethodName = "/sysarmor.analytics.v1.Link1/Stream"
)

// Link1Client is the client API for Link1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Link1Client interface {
	Upload(ctx context.Context, in *UploadBatch, opts ...grpc.CallOption) (*UploadAck, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, StreamFrame], error)
}

type link1Client struct {
	cc grpc.ClientConnInterface
}

func NewLink1Client(cc grpc.ClientConnInterface) Link1Client {
	return &link1Client{cc}
}

func (c *link1Client) Upload(ctx context.Context, in *UploadBatch, opts ...grpc.CallOption) (*UploadAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAck)
	err := c.cc.Invoke(ctx, Link1_Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *link1Client) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, StreamFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Link1_ServiceDesc.Streams[0], Link1_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFrame, StreamFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Link1_StreamClient = grpc.BidiStreamingClient[StreamFrame, StreamFrame]

// Link1Server is the server API for Link1 service.
// All implementations must embed UnimplementedLink1Server
// for forward compatibility.
type Link1Server interface {
	Upload(context.Context, *UploadBatch) (*UploadAck, error)
	Stream(grpc.BidiStreamingServer[StreamFrame, StreamFrame]) error
	mustEmbedUnimplementedLink1Server()
}

// UnimplementedLink1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLink1Server struct{}

func (UnimplementedLink1Server) Upload(context.Context, *UploadBatch) (*UploadAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedLink1Server) Stream(grpc.BidiStreamingServer[StreamFrame, StreamFrame]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedLink1Server) mustEmbedUnimplementedLink1Server() {}
func (UnimplementedLink1Server) testEmbeddedByValue()               {}

// UnsafeLink1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Link1Server will
// result in compilation errors.
type UnsafeLink1Server interface {
	mustEmbedUnimplementedLink1Server()
}

func RegisterLink1Server(s grpc.ServiceRegistrar, srv Link1Server) {
	// If the following call panics, it indicates UnimplementedLink1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Link1_ServiceDesc, srv)
}

func _Link1_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Link1Server).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Link1_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Link1Server).Upload(ctx, req.(*UploadBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link1_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Link1Server).Stream(&grpc.GenericServerStream[StreamFrame, StreamFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Link1_StreamServer = grpc.BidiStreamingServer[StreamFrame, StreamFrame]

// Link1_ServiceDesc is the grpc.ServiceDesc for Link1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Link1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysarmor.analytics.v1.Link1",
	HandlerType: (*Link1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _Link1_Upload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Link1_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/analytics/v1/link1.proto",
}
