// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/analytics/v1/link1.proto

package analyticsv1

import (
	v1 "github.com/sysarmor/sysarmor-next-project/api/proto/event/v1"
	v11 "github.com/sysarmor/sysarmor-next-project/api/proto/signal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_api_proto_analytics_v1_link1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_v1_link1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_v1_link1_proto_rawDescGZIP(), []int{0}
}

func (x *AgentHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHello) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AgentHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentHello) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type UploadBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentHello            `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Events        []*v1.CanonicalEvent   `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	Signals       []*v11.Signal          `protobuf:"bytes,3,rep,name=signals,proto3" json:"signals,omitempty"`
	BatchId       string                 `protobuf:"bytes,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBatch) Reset() {
	*x = UploadBatch{}
	mi := &file_api_proto_analytics_v1_link1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBatch) ProtoMessage() {}

func (x *UploadBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_v1_link1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBatch.ProtoReflect.Descriptor instead.
func (*UploadBatch) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_v1_link1_proto_rawDescGZIP(), []int{1}
}

func (x *UploadBatch) GetAgent() *AgentHello {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *UploadBatch) GetEvents() []*v1.CanonicalEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *UploadBatch) GetSignals() []*v11.Signal {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *UploadBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type UploadAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AcceptedEvents  uint64                 `protobuf:"varint,3,opt,name=accepted_events,json=acceptedEvents,proto3" json:"accepted_events,omitempty"`
	AcceptedSignals uint64                 `protobuf:"varint,4,opt,name=accepted_signals,json=acceptedSignals,proto3" json:"accepted_signals,omitempty"`
	BatchId         string                 `protobuf:"bytes,5,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadAck) Reset() {
	*x = UploadAck{}
	mi := &file_api_proto_analytics_v1_link1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAck) ProtoMessage() {}

func (x *UploadAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_v1_link1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAck.ProtoReflect.Descriptor instead.
func (*UploadAck) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_v1_link1_proto_rawDescGZIP(), []int{2}
}

func (x *UploadAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UploadAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadAck) GetAcceptedEvents() uint64 {
	if x != nil {
		return x.AcceptedEvents
	}
	return 0
}

func (x *UploadAck) GetAcceptedSignals() uint64 {
	if x != nil {
		return x.AcceptedSignals
	}
	return 0
}

func (x *UploadAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

var File_api_proto_analytics_v1_link1_proto protoreflect.FileDescriptor

const file_api_proto_analytics_v1_link1_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/analytics/v1/link1.proto\x12\x15sysarmor.analytics.v1\x1a\x1eapi/proto/event/v1/event.proto\x1a api/proto/signal/v1/signal.proto\"w\n" +
	"\n" +
	"AgentHello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"\xd2\x01\n" +
	"\vUploadBatch\x127\n" +
	"\x05agent\x18\x01 \x01(\v2!.sysarmor.analytics.v1.AgentHelloR\x05agent\x129\n" +
	"\x06events\x18\x02 \x03(\v2!.sysarmor.event.v1.CanonicalEventR\x06events\x124\n" +
	"\asignals\x18\x03 \x03(\v2\x1a.sysarmor.signal.v1.SignalR\asignals\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\tR\abatchId\"\xa4\x01\n" +
	"\tUploadAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0faccepted_events\x18\x03 \x01(\x04R\x0eacceptedEvents\x12)\n" +
	"\x10accepted_signals\x18\x04 \x01(\x04R\x0facceptedSignals\x12\x19\n" +
	"\bbatch_id\x18\x05 \x01(\tR\abatchId2W\n" +
	"\x05Link1\x12N\n" +
	"\x06Upload\x12\".sysarmor.analytics.v1.UploadBatch\x1a .sysarmor.analytics.v1.UploadAckBNZLgithub.com/sysarmor/sysarmor-next-project/api/proto/analytics/v1;analyticsv1b\x06proto3"

var (
	file_api_proto_analytics_v1_link1_proto_rawDescOnce sync.Once
	file_api_proto_analytics_v1_link1_proto_rawDescData []byte
)

func file_api_proto_analytics_v1_link1_proto_rawDescGZIP() []byte {
	file_api_proto_analytics_v1_link1_proto_rawDescOnce.Do(func() {
		file_api_proto_analytics_v1_link1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_analytics_v1_link1_proto_rawDesc), len(file_api_proto_analytics_v1_link1_proto_rawDesc)))
	})
	return file_api_proto_analytics_v1_link1_proto_rawDescData
}

var file_api_proto_analytics_v1_link1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_analytics_v1_link1_proto_goTypes = []any{
	(*AgentHello)(nil),        // 0: sysarmor.analytics.v1.AgentHello
	(*UploadBatch)(nil),       // 1: sysarmor.analytics.v1.UploadBatch
	(*UploadAck)(nil),         // 2: sysarmor.analytics.v1.UploadAck
	(*v1.CanonicalEvent)(nil), // 3: sysarmor.event.v1.CanonicalEvent
	(*v11.Signal)(nil),        // 4: sysarmor.signal.v1.Signal
}
var file_api_proto_analytics_v1_link1_proto_depIdxs = []int32{
	0, // 0: sysarmor.analytics.v1.UploadBatch.agent:type_name -> sysarmor.analytics.v1.AgentHello
	3, // 1: sysarmor.analytics.v1.UploadBatch.events:type_name -> sysarmor.event.v1.CanonicalEvent
	4, // 2: sysarmor.analytics.v1.UploadBatch.signals:type_name -> sysarmor.signal.v1.Signal
	1, // 3: sysarmor.analytics.v1.Link1.Upload:input_type -> sysarmor.analytics.v1.UploadBatch
	2, // 4: sysarmor.analytics.v1.Link1.Upload:output_type -> sysarmor.analytics.v1.UploadAck
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_analytics_v1_link1_proto_init() }
func file_api_proto_analytics_v1_link1_proto_init() {
	if File_api_proto_analytics_v1_link1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_analytics_v1_link1_proto_rawDesc), len(file_api_proto_analytics_v1_link1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_analytics_v1_link1_proto_goTypes,
		DependencyIndexes: file_api_proto_analytics_v1_link1_proto_depIdxs,
		MessageInfos:      file_api_proto_analytics_v1_link1_proto_msgTypes,
	}.Build()
	File_api_proto_analytics_v1_link1_proto = out.File
	file_api_proto_analytics_v1_link1_proto_goTypes = nil
	file_api_proto_analytics_v1_link1_proto_depIdxs = nil
}
