// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: packages/contracts/proto/controlplane/v1/agentcontrol.proto

package controlplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentControlPlaneService_Connect_FullMethodName          = "/sysarmor.controlplane.v1.AgentControlPlaneService/Connect"
	AgentControlPlaneService_Health_FullMethodName           = "/sysarmor.controlplane.v1.AgentControlPlaneService/Health"
	AgentControlPlaneService_Capability_FullMethodName       = "/sysarmor.controlplane.v1.AgentControlPlaneService/Capability"
	AgentControlPlaneService_CurrentPolicy_FullMethodName    = "/sysarmor.controlplane.v1.AgentControlPlaneService/CurrentPolicy"
	AgentControlPlaneService_ApplyPolicy_FullMethodName      = "/sysarmor.controlplane.v1.AgentControlPlaneService/ApplyPolicy"
	AgentControlPlaneService_ApplyContent_FullMethodName     = "/sysarmor.controlplane.v1.AgentControlPlaneService/ApplyContent"
	AgentControlPlaneService_ListContent_FullMethodName      = "/sysarmor.controlplane.v1.AgentControlPlaneService/ListContent"
	AgentControlPlaneService_GetContent_FullMethodName       = "/sysarmor.controlplane.v1.AgentControlPlaneService/GetContent"
	AgentControlPlaneService_GetEvent_FullMethodName         = "/sysarmor.controlplane.v1.AgentControlPlaneService/GetEvent"
	AgentControlPlaneService_DebugProfile_FullMethodName     = "/sysarmor.controlplane.v1.AgentControlPlaneService/DebugProfile"
	AgentControlPlaneService_WatchEvents_FullMethodName      = "/sysarmor.controlplane.v1.AgentControlPlaneService/WatchEvents"
	AgentControlPlaneService_WatchSignals_FullMethodName     = "/sysarmor.controlplane.v1.AgentControlPlaneService/WatchSignals"
	AgentControlPlaneService_Enroll_FullMethodName           = "/sysarmor.controlplane.v1.AgentControlPlaneService/Enroll"
	AgentControlPlaneService_Unenroll_FullMethodName         = "/sysarmor.controlplane.v1.AgentControlPlaneService/Unenroll"
	AgentControlPlaneService_RevokeEnrollment_FullMethodName = "/sysarmor.controlplane.v1.AgentControlPlaneService/RevokeEnrollment"
)

// AgentControlPlaneServiceClient is the client API for AgentControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentControlPlaneServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlFrame, ControlFrame], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Capability(ctx context.Context, in *CapabilityRequest, opts ...grpc.CallOption) (*CapabilityResponse, error)
	CurrentPolicy(ctx context.Context, in *CurrentPolicyRequest, opts ...grpc.CallOption) (*CurrentPolicyResponse, error)
	ApplyPolicy(ctx context.Context, in *ApplyPolicyRequest, opts ...grpc.CallOption) (*ControlAck, error)
	ApplyContent(ctx context.Context, in *ApplyContentRequest, opts ...grpc.CallOption) (*ControlAck, error)
	ListContent(ctx context.Context, in *ListContentRequest, opts ...grpc.CallOption) (*ListContentResponse, error)
	GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*ContentGetResponse, error)
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*EventGetResponse, error)
	DebugProfile(ctx context.Context, in *DebugProfileRequest, opts ...grpc.CallOption) (*DebugProfileResponse, error)
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventFrame], error)
	WatchSignals(ctx context.Context, in *WatchSignalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignalFrame], error)
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*ControlAck, error)
	Unenroll(ctx context.Context, in *UnenrollRequest, opts ...grpc.CallOption) (*ControlAck, error)
	RevokeEnrollment(ctx context.Context, in *RevokeEnrollmentRequest, opts ...grpc.CallOption) (*RevokeEnrollmentResponse, error)
}

type agentControlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlPlaneServiceClient(cc grpc.ClientConnInterface) AgentControlPlaneServiceClient {
	return &agentControlPlaneServiceClient{cc}
}

func (c *agentControlPlaneServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlFrame, ControlFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControlPlaneService_ServiceDesc.Streams[0], AgentControlPlaneService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlFrame, ControlFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlPlaneService_ConnectClient = grpc.BidiStreamingClient[ControlFrame, ControlFrame]

func (c *agentControlPlaneServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneServiceClient) Capability(ctx context.Context, in *CapabilityRequest, opts ...grpc.CallOption) (*CapabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilityResponse)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_Capability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneServiceClient) CurrentPolicy(ctx context.Context, in *CurrentPolicyRequest, opts ...grpc.CallOption) (*CurrentPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrentPolicyResponse)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_CurrentPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneServiceClient) ApplyPolicy(ctx context.Context, in *ApplyPolicyRequest, opts ...grpc.CallOption) (*ControlAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlAck)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_ApplyPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneServiceClient) ApplyContent(ctx context.Context, in *ApplyContentRequest, opts ...grpc.CallOption) (*ControlAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlAck)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_ApplyContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneServiceClient) ListContent(ctx context.Context, in *ListContentRequest, opts ...grpc.CallOption) (*ListContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentResponse)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_ListContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneServiceClient) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*ContentGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentGetResponse)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_GetContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneServiceClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*EventGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventGetResponse)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneServiceClient) DebugProfile(ctx context.Context, in *DebugProfileRequest, opts ...grpc.CallOption) (*DebugProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebugProfileResponse)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_DebugProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneServiceClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControlPlaneService_ServiceDesc.Streams[1], AgentControlPlaneService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, EventFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlPlaneService_WatchEventsClient = grpc.ServerStreamingClient[EventFrame]

func (c *agentControlPlaneServiceClient) WatchSignals(ctx context.Context, in *WatchSignalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignalFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControlPlaneService_ServiceDesc.Streams[2], AgentControlPlaneService_WatchSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchSignalsRequest, SignalFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlPlaneService_WatchSignalsClient = grpc.ServerStreamingClient[SignalFrame]

func (c *agentControlPlaneServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*ControlAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlAck)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneServiceClient) Unenroll(ctx context.Context, in *UnenrollRequest, opts ...grpc.CallOption) (*ControlAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlAck)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_Unenroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlPlaneServiceClient) RevokeEnrollment(ctx context.Context, in *RevokeEnrollmentRequest, opts ...grpc.CallOption) (*RevokeEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeEnrollmentResponse)
	err := c.cc.Invoke(ctx, AgentControlPlaneService_RevokeEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentControlPlaneServiceServer is the server API for AgentControlPlaneService service.
// All implementations must embed UnimplementedAgentControlPlaneServiceServer
// for forward compatibility.
type AgentControlPlaneServiceServer interface {
	Connect(grpc.BidiStreamingServer[ControlFrame, ControlFrame]) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Capability(context.Context, *CapabilityRequest) (*CapabilityResponse, error)
	CurrentPolicy(context.Context, *CurrentPolicyRequest) (*CurrentPolicyResponse, error)
	ApplyPolicy(context.Context, *ApplyPolicyRequest) (*ControlAck, error)
	ApplyContent(context.Context, *ApplyContentRequest) (*ControlAck, error)
	ListContent(context.Context, *ListContentRequest) (*ListContentResponse, error)
	GetContent(context.Context, *GetContentRequest) (*ContentGetResponse, error)
	GetEvent(context.Context, *GetEventRequest) (*EventGetResponse, error)
	DebugProfile(context.Context, *DebugProfileRequest) (*DebugProfileResponse, error)
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[EventFrame]) error
	WatchSignals(*WatchSignalsRequest, grpc.ServerStreamingServer[SignalFrame]) error
	Enroll(context.Context, *EnrollRequest) (*ControlAck, error)
	Unenroll(context.Context, *UnenrollRequest) (*ControlAck, error)
	RevokeEnrollment(context.Context, *RevokeEnrollmentRequest) (*RevokeEnrollmentResponse, error)
	mustEmbedUnimplementedAgentControlPlaneServiceServer()
}

// UnimplementedAgentControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlPlaneServiceServer struct{}

func (UnimplementedAgentControlPlaneServiceServer) Connect(grpc.BidiStreamingServer[ControlFrame, ControlFrame]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) Capability(context.Context, *CapabilityRequest) (*CapabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capability not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) CurrentPolicy(context.Context, *CurrentPolicyRequest) (*CurrentPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CurrentPolicy not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) ApplyPolicy(context.Context, *ApplyPolicyRequest) (*ControlAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPolicy not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) ApplyContent(context.Context, *ApplyContentRequest) (*ControlAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyContent not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) ListContent(context.Context, *ListContentRequest) (*ListContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContent not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) GetContent(context.Context, *GetContentRequest) (*ContentGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContent not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) GetEvent(context.Context, *GetEventRequest) (*EventGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) DebugProfile(context.Context, *DebugProfileRequest) (*DebugProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DebugProfile not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[EventFrame]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) WatchSignals(*WatchSignalsRequest, grpc.ServerStreamingServer[SignalFrame]) error {
	return status.Error(codes.Unimplemented, "method WatchSignals not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) Enroll(context.Context, *EnrollRequest) (*ControlAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) Unenroll(context.Context, *UnenrollRequest) (*ControlAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Unenroll not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) RevokeEnrollment(context.Context, *RevokeEnrollmentRequest) (*RevokeEnrollmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeEnrollment not implemented")
}
func (UnimplementedAgentControlPlaneServiceServer) mustEmbedUnimplementedAgentControlPlaneServiceServer() {
}
func (UnimplementedAgentControlPlaneServiceServer) testEmbeddedByValue() {}

// UnsafeAgentControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlPlaneServiceServer will
// result in compilation errors.
type UnsafeAgentControlPlaneServiceServer interface {
	mustEmbedUnimplementedAgentControlPlaneServiceServer()
}

func RegisterAgentControlPlaneServiceServer(s grpc.ServiceRegistrar, srv AgentControlPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControlPlaneService_ServiceDesc, srv)
}

func _AgentControlPlaneService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlPlaneServiceServer).Connect(&grpc.GenericServerStream[ControlFrame, ControlFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlPlaneService_ConnectServer = grpc.BidiStreamingServer[ControlFrame, ControlFrame]

func _AgentControlPlaneService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlaneService_Capability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).Capability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_Capability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).Capability(ctx, req.(*CapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlaneService_CurrentPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).CurrentPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_CurrentPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).CurrentPolicy(ctx, req.(*CurrentPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlaneService_ApplyPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).ApplyPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_ApplyPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).ApplyPolicy(ctx, req.(*ApplyPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlaneService_ApplyContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).ApplyContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_ApplyContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).ApplyContent(ctx, req.(*ApplyContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlaneService_ListContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).ListContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_ListContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).ListContent(ctx, req.(*ListContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlaneService_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_GetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).GetContent(ctx, req.(*GetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlaneService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlaneService_DebugProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).DebugProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_DebugProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).DebugProfile(ctx, req.(*DebugProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlaneService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentControlPlaneServiceServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, EventFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlPlaneService_WatchEventsServer = grpc.ServerStreamingServer[EventFrame]

func _AgentControlPlaneService_WatchSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchSignalsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentControlPlaneServiceServer).WatchSignals(m, &grpc.GenericServerStream[WatchSignalsRequest, SignalFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlPlaneService_WatchSignalsServer = grpc.ServerStreamingServer[SignalFrame]

func _AgentControlPlaneService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlaneService_Unenroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnenrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).Unenroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_Unenroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).Unenroll(ctx, req.(*UnenrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlPlaneService_RevokeEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlPlaneServiceServer).RevokeEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlPlaneService_RevokeEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlPlaneServiceServer).RevokeEnrollment(ctx, req.(*RevokeEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentControlPlaneService_ServiceDesc is the grpc.ServiceDesc for AgentControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysarmor.controlplane.v1.AgentControlPlaneService",
	HandlerType: (*AgentControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AgentControlPlaneService_Health_Handler,
		},
		{
			MethodName: "Capability",
			Handler:    _AgentControlPlaneService_Capability_Handler,
		},
		{
			MethodName: "CurrentPolicy",
			Handler:    _AgentControlPlaneService_CurrentPolicy_Handler,
		},
		{
			MethodName: "ApplyPolicy",
			Handler:    _AgentControlPlaneService_ApplyPolicy_Handler,
		},
		{
			MethodName: "ApplyContent",
			Handler:    _AgentControlPlaneService_ApplyContent_Handler,
		},
		{
			MethodName: "ListContent",
			Handler:    _AgentControlPlaneService_ListContent_Handler,
		},
		{
			MethodName: "GetContent",
			Handler:    _AgentControlPlaneService_GetContent_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _AgentControlPlaneService_GetEvent_Handler,
		},
		{
			MethodName: "DebugProfile",
			Handler:    _AgentControlPlaneService_DebugProfile_Handler,
		},
		{
			MethodName: "Enroll",
			Handler:    _AgentControlPlaneService_Enroll_Handler,
		},
		{
			MethodName: "Unenroll",
			Handler:    _AgentControlPlaneService_Unenroll_Handler,
		},
		{
			MethodName: "RevokeEnrollment",
			Handler:    _AgentControlPlaneService_RevokeEnrollment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentControlPlaneService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchEvents",
			Handler:       _AgentControlPlaneService_WatchEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchSignals",
			Handler:       _AgentControlPlaneService_WatchSignals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "packages/contracts/proto/controlplane/v1/agentcontrol.proto",
}
