// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: api/proto/dataplane/v1/dataplane.proto

package dataplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentDataPlaneService_StreamBatches_FullMethodName = "/sysarmor.dataplane.v1.AgentDataPlaneService/StreamBatches"
)

// AgentDataPlaneServiceClient is the client API for AgentDataPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentDataPlaneServiceClient interface {
	StreamBatches(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataBatch, DataAck], error)
}

type agentDataPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentDataPlaneServiceClient(cc grpc.ClientConnInterface) AgentDataPlaneServiceClient {
	return &agentDataPlaneServiceClient{cc}
}

func (c *agentDataPlaneServiceClient) StreamBatches(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataBatch, DataAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentDataPlaneService_ServiceDesc.Streams[0], AgentDataPlaneService_StreamBatches_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataBatch, DataAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentDataPlaneService_StreamBatchesClient = grpc.BidiStreamingClient[DataBatch, DataAck]

// AgentDataPlaneServiceServer is the server API for AgentDataPlaneService service.
// All implementations must embed UnimplementedAgentDataPlaneServiceServer
// for forward compatibility.
type AgentDataPlaneServiceServer interface {
	StreamBatches(grpc.BidiStreamingServer[DataBatch, DataAck]) error
	mustEmbedUnimplementedAgentDataPlaneServiceServer()
}

// UnimplementedAgentDataPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentDataPlaneServiceServer struct{}

func (UnimplementedAgentDataPlaneServiceServer) StreamBatches(grpc.BidiStreamingServer[DataBatch, DataAck]) error {
	return status.Error(codes.Unimplemented, "method StreamBatches not implemented")
}
func (UnimplementedAgentDataPlaneServiceServer) mustEmbedUnimplementedAgentDataPlaneServiceServer() {}
func (UnimplementedAgentDataPlaneServiceServer) testEmbeddedByValue()                               {}

// UnsafeAgentDataPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentDataPlaneServiceServer will
// result in compilation errors.
type UnsafeAgentDataPlaneServiceServer interface {
	mustEmbedUnimplementedAgentDataPlaneServiceServer()
}

func RegisterAgentDataPlaneServiceServer(s grpc.ServiceRegistrar, srv AgentDataPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentDataPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentDataPlaneService_ServiceDesc, srv)
}

func _AgentDataPlaneService_StreamBatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentDataPlaneServiceServer).StreamBatches(&grpc.GenericServerStream[DataBatch, DataAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentDataPlaneService_StreamBatchesServer = grpc.BidiStreamingServer[DataBatch, DataAck]

// AgentDataPlaneService_ServiceDesc is the grpc.ServiceDesc for AgentDataPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentDataPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysarmor.dataplane.v1.AgentDataPlaneService",
	HandlerType: (*AgentDataPlaneServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBatches",
			Handler:       _AgentDataPlaneService_StreamBatches_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/dataplane/v1/dataplane.proto",
}
