// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: api/proto/dataplane/v1/dataplane.proto

package dataplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentDataPlaneService_AppendBatch_FullMethodName = "/sysarmor.dataplane.v1.AgentDataPlaneService/AppendBatch"
)

// AgentDataPlaneServiceClient is the client API for AgentDataPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentDataPlaneServiceClient interface {
	AppendBatch(ctx context.Context, in *DataBatch, opts ...grpc.CallOption) (*DataAck, error)
}

type agentDataPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentDataPlaneServiceClient(cc grpc.ClientConnInterface) AgentDataPlaneServiceClient {
	return &agentDataPlaneServiceClient{cc}
}

func (c *agentDataPlaneServiceClient) AppendBatch(ctx context.Context, in *DataBatch, opts ...grpc.CallOption) (*DataAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataAck)
	err := c.cc.Invoke(ctx, AgentDataPlaneService_AppendBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentDataPlaneServiceServer is the server API for AgentDataPlaneService service.
// All implementations must embed UnimplementedAgentDataPlaneServiceServer
// for forward compatibility.
type AgentDataPlaneServiceServer interface {
	AppendBatch(context.Context, *DataBatch) (*DataAck, error)
	mustEmbedUnimplementedAgentDataPlaneServiceServer()
}

// UnimplementedAgentDataPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentDataPlaneServiceServer struct{}

func (UnimplementedAgentDataPlaneServiceServer) AppendBatch(context.Context, *DataBatch) (*DataAck, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendBatch not implemented")
}
func (UnimplementedAgentDataPlaneServiceServer) mustEmbedUnimplementedAgentDataPlaneServiceServer() {}
func (UnimplementedAgentDataPlaneServiceServer) testEmbeddedByValue()                               {}

// UnsafeAgentDataPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentDataPlaneServiceServer will
// result in compilation errors.
type UnsafeAgentDataPlaneServiceServer interface {
	mustEmbedUnimplementedAgentDataPlaneServiceServer()
}

func RegisterAgentDataPlaneServiceServer(s grpc.ServiceRegistrar, srv AgentDataPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentDataPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentDataPlaneService_ServiceDesc, srv)
}

func _AgentDataPlaneService_AppendBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentDataPlaneServiceServer).AppendBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentDataPlaneService_AppendBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentDataPlaneServiceServer).AppendBatch(ctx, req.(*DataBatch))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentDataPlaneService_ServiceDesc is the grpc.ServiceDesc for AgentDataPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentDataPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysarmor.dataplane.v1.AgentDataPlaneService",
	HandlerType: (*AgentDataPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendBatch",
			Handler:    _AgentDataPlaneService_AppendBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/dataplane/v1/dataplane.proto",
}
