// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/event/v1/event.proto

package eventv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	EventKind_EVENT_KIND_EXEC        EventKind = 1
	EventKind_EVENT_KIND_EXIT        EventKind = 2
	EventKind_EVENT_KIND_FORK        EventKind = 3
	EventKind_EVENT_KIND_OPEN        EventKind = 4
	EventKind_EVENT_KIND_WRITE       EventKind = 5
	EventKind_EVENT_KIND_CHMOD       EventKind = 6
	EventKind_EVENT_KIND_CONNECT     EventKind = 7
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "EVENT_KIND_EXEC",
		2: "EVENT_KIND_EXIT",
		3: "EVENT_KIND_FORK",
		4: "EVENT_KIND_OPEN",
		5: "EVENT_KIND_WRITE",
		6: "EVENT_KIND_CHMOD",
		7: "EVENT_KIND_CONNECT",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"EVENT_KIND_EXEC":        1,
		"EVENT_KIND_EXIT":        2,
		"EVENT_KIND_FORK":        3,
		"EVENT_KIND_OPEN":        4,
		"EVENT_KIND_WRITE":       5,
		"EVENT_KIND_CHMOD":       6,
		"EVENT_KIND_CONNECT":     7,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_event_v1_event_proto_enumTypes[0].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_api_proto_event_v1_event_proto_enumTypes[0]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_event_v1_event_proto_rawDescGZIP(), []int{0}
}

type ProcessRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StableId      string                 `protobuf:"bytes,1,opt,name=stable_id,json=stableId,proto3" json:"stable_id,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Binary        string                 `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`
	Argv          []string               `protobuf:"bytes,4,rep,name=argv,proto3" json:"argv,omitempty"`
	Uid           uint32                 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	StartTimeNs   uint64                 `protobuf:"varint,6,opt,name=start_time_ns,json=startTimeNs,proto3" json:"start_time_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRef) Reset() {
	*x = ProcessRef{}
	mi := &file_api_proto_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRef) ProtoMessage() {}

func (x *ProcessRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRef.ProtoReflect.Descriptor instead.
func (*ProcessRef) Descriptor() ([]byte, []int) {
	return file_api_proto_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRef) GetStableId() string {
	if x != nil {
		return x.StableId
	}
	return ""
}

func (x *ProcessRef) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessRef) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *ProcessRef) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ProcessRef) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProcessRef) GetStartTimeNs() uint64 {
	if x != nil {
		return x.StartTimeNs
	}
	return 0
}

type ObjectRef struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Kind               string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	FilePath           string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	SocketAddr         string                 `protobuf:"bytes,3,opt,name=socket_addr,json=socketAddr,proto3" json:"socket_addr,omitempty"`
	TargetProcStableId string                 `protobuf:"bytes,4,opt,name=target_proc_stable_id,json=targetProcStableId,proto3" json:"target_proc_stable_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	mi := &file_api_proto_event_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_event_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_api_proto_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ObjectRef) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ObjectRef) GetSocketAddr() string {
	if x != nil {
		return x.SocketAddr
	}
	return ""
}

func (x *ObjectRef) GetTargetProcStableId() string {
	if x != nil {
		return x.TargetProcStableId
	}
	return ""
}

type CanonicalEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Seq            uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	AgentId        string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId         string                 `protobuf:"bytes,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Scenario       string                 `protobuf:"bytes,5,opt,name=scenario,proto3" json:"scenario,omitempty"`
	MonoNs         uint64                 `protobuf:"varint,6,opt,name=mono_ns,json=monoNs,proto3" json:"mono_ns,omitempty"`
	Kind           EventKind              `protobuf:"varint,7,opt,name=kind,proto3,enum=sysarmor.event.v1.EventKind" json:"kind,omitempty"`
	SubjectProc    *ProcessRef            `protobuf:"bytes,8,opt,name=subject_proc,json=subjectProc,proto3" json:"subject_proc,omitempty"`
	Object         *ObjectRef             `protobuf:"bytes,9,opt,name=object,proto3" json:"object,omitempty"`
	ParentStableId string                 `protobuf:"bytes,10,opt,name=parent_stable_id,json=parentStableId,proto3" json:"parent_stable_id,omitempty"`
	LineageId      string                 `protobuf:"bytes,11,opt,name=lineage_id,json=lineageId,proto3" json:"lineage_id,omitempty"`
	RawRef         string                 `protobuf:"bytes,12,opt,name=raw_ref,json=rawRef,proto3" json:"raw_ref,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CanonicalEvent) Reset() {
	*x = CanonicalEvent{}
	mi := &file_api_proto_event_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanonicalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanonicalEvent) ProtoMessage() {}

func (x *CanonicalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_event_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanonicalEvent.ProtoReflect.Descriptor instead.
func (*CanonicalEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_event_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *CanonicalEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CanonicalEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CanonicalEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CanonicalEvent) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CanonicalEvent) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *CanonicalEvent) GetMonoNs() uint64 {
	if x != nil {
		return x.MonoNs
	}
	return 0
}

func (x *CanonicalEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *CanonicalEvent) GetSubjectProc() *ProcessRef {
	if x != nil {
		return x.SubjectProc
	}
	return nil
}

func (x *CanonicalEvent) GetObject() *ObjectRef {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *CanonicalEvent) GetParentStableId() string {
	if x != nil {
		return x.ParentStableId
	}
	return ""
}

func (x *CanonicalEvent) GetLineageId() string {
	if x != nil {
		return x.LineageId
	}
	return ""
}

func (x *CanonicalEvent) GetRawRef() string {
	if x != nil {
		return x.RawRef
	}
	return ""
}

var File_api_proto_event_v1_event_proto protoreflect.FileDescriptor

const file_api_proto_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/event/v1/event.proto\x12\x11sysarmor.event.v1\"\x9d\x01\n" +
	"\n" +
	"ProcessRef\x12\x1b\n" +
	"\tstable_id\x18\x01 \x01(\tR\bstableId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x16\n" +
	"\x06binary\x18\x03 \x01(\tR\x06binary\x12\x12\n" +
	"\x04argv\x18\x04 \x03(\tR\x04argv\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\rR\x03uid\x12\"\n" +
	"\rstart_time_ns\x18\x06 \x01(\x04R\vstartTimeNs\"\x90\x01\n" +
	"\tObjectRef\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vsocket_addr\x18\x03 \x01(\tR\n" +
	"socketAddr\x121\n" +
	"\x15target_proc_stable_id\x18\x04 \x01(\tR\x12targetProcStableId\"\xa7\x03\n" +
	"\x0eCanonicalEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x04 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bscenario\x18\x05 \x01(\tR\bscenario\x12\x17\n" +
	"\amono_ns\x18\x06 \x01(\x04R\x06monoNs\x120\n" +
	"\x04kind\x18\a \x01(\x0e2\x1c.sysarmor.event.v1.EventKindR\x04kind\x12@\n" +
	"\fsubject_proc\x18\b \x01(\v2\x1d.sysarmor.event.v1.ProcessRefR\vsubjectProc\x124\n" +
	"\x06object\x18\t \x01(\v2\x1c.sysarmor.event.v1.ObjectRefR\x06object\x12(\n" +
	"\x10parent_stable_id\x18\n" +
	" \x01(\tR\x0eparentStableId\x12\x1d\n" +
	"\n" +
	"lineage_id\x18\v \x01(\tR\tlineageId\x12\x17\n" +
	"\araw_ref\x18\f \x01(\tR\x06rawRef*\xbf\x01\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fEVENT_KIND_EXEC\x10\x01\x12\x13\n" +
	"\x0fEVENT_KIND_EXIT\x10\x02\x12\x13\n" +
	"\x0fEVENT_KIND_FORK\x10\x03\x12\x13\n" +
	"\x0fEVENT_KIND_OPEN\x10\x04\x12\x14\n" +
	"\x10EVENT_KIND_WRITE\x10\x05\x12\x14\n" +
	"\x10EVENT_KIND_CHMOD\x10\x06\x12\x16\n" +
	"\x12EVENT_KIND_CONNECT\x10\aBFZDgithub.com/sysarmor/sysarmor-next-project/api/proto/event/v1;eventv1b\x06proto3"

var (
	file_api_proto_event_v1_event_proto_rawDescOnce sync.Once
	file_api_proto_event_v1_event_proto_rawDescData []byte
)

func file_api_proto_event_v1_event_proto_rawDescGZIP() []byte {
	file_api_proto_event_v1_event_proto_rawDescOnce.Do(func() {
		file_api_proto_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_event_v1_event_proto_rawDesc), len(file_api_proto_event_v1_event_proto_rawDesc)))
	})
	return file_api_proto_event_v1_event_proto_rawDescData
}

var file_api_proto_event_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_event_v1_event_proto_goTypes = []any{
	(EventKind)(0),         // 0: sysarmor.event.v1.EventKind
	(*ProcessRef)(nil),     // 1: sysarmor.event.v1.ProcessRef
	(*ObjectRef)(nil),      // 2: sysarmor.event.v1.ObjectRef
	(*CanonicalEvent)(nil), // 3: sysarmor.event.v1.CanonicalEvent
}
var file_api_proto_event_v1_event_proto_depIdxs = []int32{
	0, // 0: sysarmor.event.v1.CanonicalEvent.kind:type_name -> sysarmor.event.v1.EventKind
	1, // 1: sysarmor.event.v1.CanonicalEvent.subject_proc:type_name -> sysarmor.event.v1.ProcessRef
	2, // 2: sysarmor.event.v1.CanonicalEvent.object:type_name -> sysarmor.event.v1.ObjectRef
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_event_v1_event_proto_init() }
func file_api_proto_event_v1_event_proto_init() {
	if File_api_proto_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_event_v1_event_proto_rawDesc), len(file_api_proto_event_v1_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_event_v1_event_proto_goTypes,
		DependencyIndexes: file_api_proto_event_v1_event_proto_depIdxs,
		EnumInfos:         file_api_proto_event_v1_event_proto_enumTypes,
		MessageInfos:      file_api_proto_event_v1_event_proto_msgTypes,
	}.Build()
	File_api_proto_event_v1_event_proto = out.File
	file_api_proto_event_v1_event_proto_goTypes = nil
	file_api_proto_event_v1_event_proto_depIdxs = nil
}
