// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/control/v1/agentcontrol.proto

package controlv1

import (
	v1 "github.com/sysarmor/sysarmor-next-project/api/proto/event/v1"
	v11 "github.com/sysarmor/sysarmor-next-project/api/proto/signal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Scope) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type RequestContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{1}
}

func (x *RequestContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RequestContext) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RequestContext) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type SensorCapability struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Backend         string                 `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SupportsExec    bool                   `protobuf:"varint,3,opt,name=supports_exec,json=supportsExec,proto3" json:"supports_exec,omitempty"`
	SupportsConnect bool                   `protobuf:"varint,4,opt,name=supports_connect,json=supportsConnect,proto3" json:"supports_connect,omitempty"`
	SupportsFile    bool                   `protobuf:"varint,5,opt,name=supports_file,json=supportsFile,proto3" json:"supports_file,omitempty"`
	SupportsEnforce bool                   `protobuf:"varint,6,opt,name=supports_enforce,json=supportsEnforce,proto3" json:"supports_enforce,omitempty"`
	SupportsHealth  bool                   `protobuf:"varint,7,opt,name=supports_health,json=supportsHealth,proto3" json:"supports_health,omitempty"`
	KernelRelease   string                 `protobuf:"bytes,8,opt,name=kernel_release,json=kernelRelease,proto3" json:"kernel_release,omitempty"`
	BtfAvailable    bool                   `protobuf:"varint,9,opt,name=btf_available,json=btfAvailable,proto3" json:"btf_available,omitempty"`
	BpffsAvailable  bool                   `protobuf:"varint,10,opt,name=bpffs_available,json=bpffsAvailable,proto3" json:"bpffs_available,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SensorCapability) Reset() {
	*x = SensorCapability{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorCapability) ProtoMessage() {}

func (x *SensorCapability) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorCapability.ProtoReflect.Descriptor instead.
func (*SensorCapability) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{2}
}

func (x *SensorCapability) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *SensorCapability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SensorCapability) GetSupportsExec() bool {
	if x != nil {
		return x.SupportsExec
	}
	return false
}

func (x *SensorCapability) GetSupportsConnect() bool {
	if x != nil {
		return x.SupportsConnect
	}
	return false
}

func (x *SensorCapability) GetSupportsFile() bool {
	if x != nil {
		return x.SupportsFile
	}
	return false
}

func (x *SensorCapability) GetSupportsEnforce() bool {
	if x != nil {
		return x.SupportsEnforce
	}
	return false
}

func (x *SensorCapability) GetSupportsHealth() bool {
	if x != nil {
		return x.SupportsHealth
	}
	return false
}

func (x *SensorCapability) GetKernelRelease() string {
	if x != nil {
		return x.KernelRelease
	}
	return ""
}

func (x *SensorCapability) GetBtfAvailable() bool {
	if x != nil {
		return x.BtfAvailable
	}
	return false
}

func (x *SensorCapability) GetBpffsAvailable() bool {
	if x != nil {
		return x.BpffsAvailable
	}
	return false
}

type CollectionBehaviorCapability struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Behavior             string                 `protobuf:"bytes,1,opt,name=behavior,proto3" json:"behavior,omitempty"`
	Fields               []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	PushdownSelectors    []string               `protobuf:"bytes,3,rep,name=pushdown_selectors,json=pushdownSelectors,proto3" json:"pushdown_selectors,omitempty"`
	AgentSideSelectors   []string               `protobuf:"bytes,4,rep,name=agent_side_selectors,json=agentSideSelectors,proto3" json:"agent_side_selectors,omitempty"`
	UnsupportedSelectors []string               `protobuf:"bytes,5,rep,name=unsupported_selectors,json=unsupportedSelectors,proto3" json:"unsupported_selectors,omitempty"`
	SensorMapping        string                 `protobuf:"bytes,6,opt,name=sensor_mapping,json=sensorMapping,proto3" json:"sensor_mapping,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CollectionBehaviorCapability) Reset() {
	*x = CollectionBehaviorCapability{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionBehaviorCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionBehaviorCapability) ProtoMessage() {}

func (x *CollectionBehaviorCapability) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionBehaviorCapability.ProtoReflect.Descriptor instead.
func (*CollectionBehaviorCapability) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{3}
}

func (x *CollectionBehaviorCapability) GetBehavior() string {
	if x != nil {
		return x.Behavior
	}
	return ""
}

func (x *CollectionBehaviorCapability) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CollectionBehaviorCapability) GetPushdownSelectors() []string {
	if x != nil {
		return x.PushdownSelectors
	}
	return nil
}

func (x *CollectionBehaviorCapability) GetAgentSideSelectors() []string {
	if x != nil {
		return x.AgentSideSelectors
	}
	return nil
}

func (x *CollectionBehaviorCapability) GetUnsupportedSelectors() []string {
	if x != nil {
		return x.UnsupportedSelectors
	}
	return nil
}

func (x *CollectionBehaviorCapability) GetSensorMapping() string {
	if x != nil {
		return x.SensorMapping
	}
	return ""
}

type SensorHealth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Backend        string                 `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	Installed      bool                   `protobuf:"varint,2,opt,name=installed,proto3" json:"installed,omitempty"`
	Running        bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	Version        string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	PolicyLoaded   bool                   `protobuf:"varint,5,opt,name=policy_loaded,json=policyLoaded,proto3" json:"policy_loaded,omitempty"`
	EventsSeen     uint64                 `protobuf:"varint,6,opt,name=events_seen,json=eventsSeen,proto3" json:"events_seen,omitempty"`
	EventsDropped  uint64                 `protobuf:"varint,7,opt,name=events_dropped,json=eventsDropped,proto3" json:"events_dropped,omitempty"`
	ParseErrors    uint64                 `protobuf:"varint,8,opt,name=parse_errors,json=parseErrors,proto3" json:"parse_errors,omitempty"`
	RestartCount   uint64                 `protobuf:"varint,9,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	LastEventAt    string                 `protobuf:"bytes,10,opt,name=last_event_at,json=lastEventAt,proto3" json:"last_event_at,omitempty"`
	LastExitReason string                 `protobuf:"bytes,11,opt,name=last_exit_reason,json=lastExitReason,proto3" json:"last_exit_reason,omitempty"`
	LastError      string                 `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SensorHealth) Reset() {
	*x = SensorHealth{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorHealth) ProtoMessage() {}

func (x *SensorHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorHealth.ProtoReflect.Descriptor instead.
func (*SensorHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{4}
}

func (x *SensorHealth) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *SensorHealth) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *SensorHealth) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *SensorHealth) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SensorHealth) GetPolicyLoaded() bool {
	if x != nil {
		return x.PolicyLoaded
	}
	return false
}

func (x *SensorHealth) GetEventsSeen() uint64 {
	if x != nil {
		return x.EventsSeen
	}
	return 0
}

func (x *SensorHealth) GetEventsDropped() uint64 {
	if x != nil {
		return x.EventsDropped
	}
	return 0
}

func (x *SensorHealth) GetParseErrors() uint64 {
	if x != nil {
		return x.ParseErrors
	}
	return 0
}

func (x *SensorHealth) GetRestartCount() uint64 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *SensorHealth) GetLastEventAt() string {
	if x != nil {
		return x.LastEventAt
	}
	return ""
}

func (x *SensorHealth) GetLastExitReason() string {
	if x != nil {
		return x.LastExitReason
	}
	return ""
}

func (x *SensorHealth) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type QueueHealth struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueuedBatches     uint32                 `protobuf:"varint,1,opt,name=queued_batches,json=queuedBatches,proto3" json:"queued_batches,omitempty"`
	QueuedBytes       int64                  `protobuf:"varint,2,opt,name=queued_bytes,json=queuedBytes,proto3" json:"queued_bytes,omitempty"`
	MaxBytes          int64                  `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	BackpressureCount uint64                 `protobuf:"varint,4,opt,name=backpressure_count,json=backpressureCount,proto3" json:"backpressure_count,omitempty"`
	DroppedBatches    uint64                 `protobuf:"varint,5,opt,name=dropped_batches,json=droppedBatches,proto3" json:"dropped_batches,omitempty"`
	DroppedBytes      uint64                 `protobuf:"varint,6,opt,name=dropped_bytes,json=droppedBytes,proto3" json:"dropped_bytes,omitempty"`
	LastError         string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueueHealth) Reset() {
	*x = QueueHealth{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueHealth) ProtoMessage() {}

func (x *QueueHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueHealth.ProtoReflect.Descriptor instead.
func (*QueueHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{5}
}

func (x *QueueHealth) GetQueuedBatches() uint32 {
	if x != nil {
		return x.QueuedBatches
	}
	return 0
}

func (x *QueueHealth) GetQueuedBytes() int64 {
	if x != nil {
		return x.QueuedBytes
	}
	return 0
}

func (x *QueueHealth) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *QueueHealth) GetBackpressureCount() uint64 {
	if x != nil {
		return x.BackpressureCount
	}
	return 0
}

func (x *QueueHealth) GetDroppedBatches() uint64 {
	if x != nil {
		return x.DroppedBatches
	}
	return 0
}

func (x *QueueHealth) GetDroppedBytes() uint64 {
	if x != nil {
		return x.DroppedBytes
	}
	return 0
}

func (x *QueueHealth) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type UploadHealth struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UploadedBatches  uint32                 `protobuf:"varint,1,opt,name=uploaded_batches,json=uploadedBatches,proto3" json:"uploaded_batches,omitempty"`
	RemainingBatches uint32                 `protobuf:"varint,2,opt,name=remaining_batches,json=remainingBatches,proto3" json:"remaining_batches,omitempty"`
	RemainingBytes   int64                  `protobuf:"varint,3,opt,name=remaining_bytes,json=remainingBytes,proto3" json:"remaining_bytes,omitempty"`
	LastError        string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UploadHealth) Reset() {
	*x = UploadHealth{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadHealth) ProtoMessage() {}

func (x *UploadHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadHealth.ProtoReflect.Descriptor instead.
func (*UploadHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{6}
}

func (x *UploadHealth) GetUploadedBatches() uint32 {
	if x != nil {
		return x.UploadedBatches
	}
	return 0
}

func (x *UploadHealth) GetRemainingBatches() uint32 {
	if x != nil {
		return x.RemainingBatches
	}
	return 0
}

func (x *UploadHealth) GetRemainingBytes() int64 {
	if x != nil {
		return x.RemainingBytes
	}
	return 0
}

func (x *UploadHealth) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type CEPHealth struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActiveGroups     uint64                 `protobuf:"varint,1,opt,name=active_groups,json=activeGroups,proto3" json:"active_groups,omitempty"`
	EvictedGroups    uint64                 `protobuf:"varint,2,opt,name=evicted_groups,json=evictedGroups,proto3" json:"evicted_groups,omitempty"`
	ExpiredGroups    uint64                 `protobuf:"varint,3,opt,name=expired_groups,json=expiredGroups,proto3" json:"expired_groups,omitempty"`
	DroppedEventRefs uint64                 `protobuf:"varint,4,opt,name=dropped_event_refs,json=droppedEventRefs,proto3" json:"dropped_event_refs,omitempty"`
	EvalErrors       uint64                 `protobuf:"varint,5,opt,name=eval_errors,json=evalErrors,proto3" json:"eval_errors,omitempty"`
	EmittedSignals   uint64                 `protobuf:"varint,6,opt,name=emitted_signals,json=emittedSignals,proto3" json:"emitted_signals,omitempty"`
	Degraded         bool                   `protobuf:"varint,7,opt,name=degraded,proto3" json:"degraded,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CEPHealth) Reset() {
	*x = CEPHealth{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEPHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEPHealth) ProtoMessage() {}

func (x *CEPHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEPHealth.ProtoReflect.Descriptor instead.
func (*CEPHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{7}
}

func (x *CEPHealth) GetActiveGroups() uint64 {
	if x != nil {
		return x.ActiveGroups
	}
	return 0
}

func (x *CEPHealth) GetEvictedGroups() uint64 {
	if x != nil {
		return x.EvictedGroups
	}
	return 0
}

func (x *CEPHealth) GetExpiredGroups() uint64 {
	if x != nil {
		return x.ExpiredGroups
	}
	return 0
}

func (x *CEPHealth) GetDroppedEventRefs() uint64 {
	if x != nil {
		return x.DroppedEventRefs
	}
	return 0
}

func (x *CEPHealth) GetEvalErrors() uint64 {
	if x != nil {
		return x.EvalErrors
	}
	return 0
}

func (x *CEPHealth) GetEmittedSignals() uint64 {
	if x != nil {
		return x.EmittedSignals
	}
	return 0
}

func (x *CEPHealth) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{8}
}

func (x *HealthRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	PolicyId      string                 `protobuf:"bytes,6,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion uint64                 `protobuf:"varint,7,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	PolicyMode    string                 `protobuf:"bytes,8,opt,name=policy_mode,json=policyMode,proto3" json:"policy_mode,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,9,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Capability    *SensorCapability      `protobuf:"bytes,10,opt,name=capability,proto3" json:"capability,omitempty"`
	Sensor        *SensorHealth          `protobuf:"bytes,11,opt,name=sensor,proto3" json:"sensor,omitempty"`
	Queue         *QueueHealth           `protobuf:"bytes,12,opt,name=queue,proto3" json:"queue,omitempty"`
	Upload        *UploadHealth          `protobuf:"bytes,13,opt,name=upload,proto3" json:"upload,omitempty"`
	ObservedAt    string                 `protobuf:"bytes,14,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Cep           *CEPHealth             `protobuf:"bytes,15,opt,name=cep,proto3" json:"cep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HealthResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HealthResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *HealthResponse) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *HealthResponse) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *HealthResponse) GetPolicyMode() string {
	if x != nil {
		return x.PolicyMode
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetCapability() *SensorCapability {
	if x != nil {
		return x.Capability
	}
	return nil
}

func (x *HealthResponse) GetSensor() *SensorHealth {
	if x != nil {
		return x.Sensor
	}
	return nil
}

func (x *HealthResponse) GetQueue() *QueueHealth {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *HealthResponse) GetUpload() *UploadHealth {
	if x != nil {
		return x.Upload
	}
	return nil
}

func (x *HealthResponse) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *HealthResponse) GetCep() *CEPHealth {
	if x != nil {
		return x.Cep
	}
	return nil
}

type CapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRequest) Reset() {
	*x = CapabilityRequest{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRequest) ProtoMessage() {}

func (x *CapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRequest.ProtoReflect.Descriptor instead.
func (*CapabilityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{10}
}

func (x *CapabilityRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type CapabilityResponse struct {
	state                    protoimpl.MessageState          `protogen:"open.v1"`
	AgentId                  string                          `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId                   string                          `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	TenantId                 string                          `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope                    *Scope                          `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Sensor                   *SensorCapability               `protobuf:"bytes,5,opt,name=sensor,proto3" json:"sensor,omitempty"`
	SupportedPolicySections  []string                        `protobuf:"bytes,6,rep,name=supported_policy_sections,json=supportedPolicySections,proto3" json:"supported_policy_sections,omitempty"`
	SupportedResponseActions []string                        `protobuf:"bytes,8,rep,name=supported_response_actions,json=supportedResponseActions,proto3" json:"supported_response_actions,omitempty"`
	CollectionBehaviors      []*CollectionBehaviorCapability `protobuf:"bytes,9,rep,name=collection_behaviors,json=collectionBehaviors,proto3" json:"collection_behaviors,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CapabilityResponse) Reset() {
	*x = CapabilityResponse{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityResponse) ProtoMessage() {}

func (x *CapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityResponse.ProtoReflect.Descriptor instead.
func (*CapabilityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{11}
}

func (x *CapabilityResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CapabilityResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CapabilityResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CapabilityResponse) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CapabilityResponse) GetSensor() *SensorCapability {
	if x != nil {
		return x.Sensor
	}
	return nil
}

func (x *CapabilityResponse) GetSupportedPolicySections() []string {
	if x != nil {
		return x.SupportedPolicySections
	}
	return nil
}

func (x *CapabilityResponse) GetSupportedResponseActions() []string {
	if x != nil {
		return x.SupportedResponseActions
	}
	return nil
}

func (x *CapabilityResponse) GetCollectionBehaviors() []*CollectionBehaviorCapability {
	if x != nil {
		return x.CollectionBehaviors
	}
	return nil
}

type CurrentPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentPolicyRequest) Reset() {
	*x = CurrentPolicyRequest{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentPolicyRequest) ProtoMessage() {}

func (x *CurrentPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentPolicyRequest.ProtoReflect.Descriptor instead.
func (*CurrentPolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{12}
}

func (x *CurrentPolicyRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type CurrentPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	EndpointRules []string               `protobuf:"bytes,6,rep,name=endpoint_rules,json=endpointRules,proto3" json:"endpoint_rules,omitempty"`
	CloudRules    []string               `protobuf:"bytes,7,rep,name=cloud_rules,json=cloudRules,proto3" json:"cloud_rules,omitempty"`
	Published     bool                   `protobuf:"varint,8,opt,name=published,proto3" json:"published,omitempty"`
	RawJson       string                 `protobuf:"bytes,9,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentPolicyResponse) Reset() {
	*x = CurrentPolicyResponse{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentPolicyResponse) ProtoMessage() {}

func (x *CurrentPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentPolicyResponse.ProtoReflect.Descriptor instead.
func (*CurrentPolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{13}
}

func (x *CurrentPolicyResponse) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *CurrentPolicyResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CurrentPolicyResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CurrentPolicyResponse) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CurrentPolicyResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CurrentPolicyResponse) GetEndpointRules() []string {
	if x != nil {
		return x.EndpointRules
	}
	return nil
}

func (x *CurrentPolicyResponse) GetCloudRules() []string {
	if x != nil {
		return x.CloudRules
	}
	return nil
}

func (x *CurrentPolicyResponse) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

func (x *CurrentPolicyResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type ApplyPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	PolicyType    string                 `protobuf:"bytes,2,opt,name=policy_type,json=policyType,proto3" json:"policy_type,omitempty"`
	PolicyJson    string                 `protobuf:"bytes,3,opt,name=policy_json,json=policyJson,proto3" json:"policy_json,omitempty"`
	DryRun        bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPolicyRequest) Reset() {
	*x = ApplyPolicyRequest{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPolicyRequest) ProtoMessage() {}

func (x *ApplyPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPolicyRequest.ProtoReflect.Descriptor instead.
func (*ApplyPolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{14}
}

func (x *ApplyPolicyRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ApplyPolicyRequest) GetPolicyType() string {
	if x != nil {
		return x.PolicyType
	}
	return ""
}

func (x *ApplyPolicyRequest) GetPolicyJson() string {
	if x != nil {
		return x.PolicyJson
	}
	return ""
}

func (x *ApplyPolicyRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type ApplyContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	ContentJson   string                 `protobuf:"bytes,2,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	DryRun        bool                   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	AllowUnsigned bool                   `protobuf:"varint,4,opt,name=allow_unsigned,json=allowUnsigned,proto3" json:"allow_unsigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyContentRequest) Reset() {
	*x = ApplyContentRequest{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyContentRequest) ProtoMessage() {}

func (x *ApplyContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyContentRequest.ProtoReflect.Descriptor instead.
func (*ApplyContentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{15}
}

func (x *ApplyContentRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ApplyContentRequest) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *ApplyContentRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *ApplyContentRequest) GetAllowUnsigned() bool {
	if x != nil {
		return x.AllowUnsigned
	}
	return false
}

type ContentRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	Signed        bool                   `protobuf:"varint,5,opt,name=signed,proto3" json:"signed,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	RawJson       string                 `protobuf:"bytes,7,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRecord) Reset() {
	*x = ContentRecord{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRecord) ProtoMessage() {}

func (x *ContentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRecord.ProtoReflect.Descriptor instead.
func (*ContentRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{16}
}

func (x *ContentRecord) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ContentRecord) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContentRecord) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ContentRecord) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ContentRecord) GetSigned() bool {
	if x != nil {
		return x.Signed
	}
	return false
}

func (x *ContentRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContentRecord) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type ListContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentRequest) Reset() {
	*x = ListContentRequest{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentRequest) ProtoMessage() {}

func (x *ListContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentRequest.ProtoReflect.Descriptor instead.
func (*ListContentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{17}
}

func (x *ListContentRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListContentRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ListContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ContentRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentResponse) Reset() {
	*x = ListContentResponse{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentResponse) ProtoMessage() {}

func (x *ListContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentResponse.ProtoReflect.Descriptor instead.
func (*ListContentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{18}
}

func (x *ListContentResponse) GetRecords() []*ContentRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{19}
}

func (x *GetContentRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetContentRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type ContentGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ContentRecord         `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentGetResponse) Reset() {
	*x = ContentGetResponse{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentGetResponse) ProtoMessage() {}

func (x *ContentGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentGetResponse.ProtoReflect.Descriptor instead.
func (*ContentGetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{20}
}

func (x *ContentGetResponse) GetRecord() *ContentRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type AppliedSection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequiresRestart bool                   `protobuf:"varint,4,opt,name=requires_restart,json=requiresRestart,proto3" json:"requires_restart,omitempty"`
	Details         []string               `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`
	ReportJson      string                 `protobuf:"bytes,6,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppliedSection) Reset() {
	*x = AppliedSection{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppliedSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedSection) ProtoMessage() {}

func (x *AppliedSection) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedSection.ProtoReflect.Descriptor instead.
func (*AppliedSection) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{21}
}

func (x *AppliedSection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppliedSection) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AppliedSection) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppliedSection) GetRequiresRestart() bool {
	if x != nil {
		return x.RequiresRestart
	}
	return false
}

func (x *AppliedSection) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *AppliedSection) GetReportJson() string {
	if x != nil {
		return x.ReportJson
	}
	return ""
}

type ControlAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	PolicyId      string                 `protobuf:"bytes,6,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion uint64                 `protobuf:"varint,7,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Sections      []*AppliedSection      `protobuf:"bytes,8,rep,name=sections,proto3" json:"sections,omitempty"`
	Details       []string               `protobuf:"bytes,9,rep,name=details,proto3" json:"details,omitempty"`
	ReportJson    string                 `protobuf:"bytes,10,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlAck) Reset() {
	*x = ControlAck{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlAck) ProtoMessage() {}

func (x *ControlAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlAck.ProtoReflect.Descriptor instead.
func (*ControlAck) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{22}
}

func (x *ControlAck) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ControlAck) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ControlAck) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ControlAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ControlAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlAck) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ControlAck) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *ControlAck) GetSections() []*AppliedSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *ControlAck) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ControlAck) GetReportJson() string {
	if x != nil {
		return x.ReportJson
	}
	return ""
}

type WatchEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Behavior      string                 `protobuf:"bytes,2,opt,name=behavior,proto3" json:"behavior,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	IncludeRecent bool                   `protobuf:"varint,4,opt,name=include_recent,json=includeRecent,proto3" json:"include_recent,omitempty"`
	SnapshotOnly  bool                   `protobuf:"varint,5,opt,name=snapshot_only,json=snapshotOnly,proto3" json:"snapshot_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{23}
}

func (x *WatchEventsRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WatchEventsRequest) GetBehavior() string {
	if x != nil {
		return x.Behavior
	}
	return ""
}

func (x *WatchEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *WatchEventsRequest) GetIncludeRecent() bool {
	if x != nil {
		return x.IncludeRecent
	}
	return false
}

func (x *WatchEventsRequest) GetSnapshotOnly() bool {
	if x != nil {
		return x.SnapshotOnly
	}
	return false
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{24}
}

func (x *GetEventRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type EventGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frame         *EventFrame            `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventGetResponse) Reset() {
	*x = EventGetResponse{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventGetResponse) ProtoMessage() {}

func (x *EventGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventGetResponse.ProtoReflect.Descriptor instead.
func (*EventGetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{25}
}

func (x *EventGetResponse) GetFrame() *EventFrame {
	if x != nil {
		return x.Frame
	}
	return nil
}

type EventFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObservedAt    string                 `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Event         *v1.CanonicalEvent     `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFrame) Reset() {
	*x = EventFrame{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFrame) ProtoMessage() {}

func (x *EventFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFrame.ProtoReflect.Descriptor instead.
func (*EventFrame) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{26}
}

func (x *EventFrame) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EventFrame) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EventFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EventFrame) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *EventFrame) GetEvent() *v1.CanonicalEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type WatchSignalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Where         string                 `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	IncludeRecent bool                   `protobuf:"varint,5,opt,name=include_recent,json=includeRecent,proto3" json:"include_recent,omitempty"`
	SnapshotOnly  bool                   `protobuf:"varint,6,opt,name=snapshot_only,json=snapshotOnly,proto3" json:"snapshot_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSignalsRequest) Reset() {
	*x = WatchSignalsRequest{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSignalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSignalsRequest) ProtoMessage() {}

func (x *WatchSignalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSignalsRequest.ProtoReflect.Descriptor instead.
func (*WatchSignalsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{27}
}

func (x *WatchSignalsRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WatchSignalsRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *WatchSignalsRequest) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

func (x *WatchSignalsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *WatchSignalsRequest) GetIncludeRecent() bool {
	if x != nil {
		return x.IncludeRecent
	}
	return false
}

func (x *WatchSignalsRequest) GetSnapshotOnly() bool {
	if x != nil {
		return x.SnapshotOnly
	}
	return false
}

type SignalFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObservedAt    string                 `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Signal        *v11.Signal            `protobuf:"bytes,5,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalFrame) Reset() {
	*x = SignalFrame{}
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalFrame) ProtoMessage() {}

func (x *SignalFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_v1_agentcontrol_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalFrame.ProtoReflect.Descriptor instead.
func (*SignalFrame) Descriptor() ([]byte, []int) {
	return file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP(), []int{28}
}

func (x *SignalFrame) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SignalFrame) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SignalFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SignalFrame) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *SignalFrame) GetSignal() *v11.Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

var File_api_proto_control_v1_agentcontrol_proto protoreflect.FileDescriptor

const file_api_proto_control_v1_agentcontrol_proto_rawDesc = "" +
	"\n" +
	"'api/proto/control/v1/agentcontrol.proto\x12\x13sysarmor.control.v1\x1a\x1eapi/proto/event/v1/event.proto\x1a api/proto/signal/v1/signal.proto\"7\n" +
	"\x05Scope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\"\x99\x01\n" +
	"\x0eRequestContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x120\n" +
	"\x05scope\x18\x04 \x01(\v2\x1a.sysarmor.control.v1.ScopeR\x05scope\"\x84\x03\n" +
	"\x10SensorCapability\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12#\n" +
	"\rsupports_exec\x18\x03 \x01(\bR\fsupportsExec\x12)\n" +
	"\x10supports_connect\x18\x04 \x01(\bR\x0fsupportsConnect\x12#\n" +
	"\rsupports_file\x18\x05 \x01(\bR\fsupportsFile\x12)\n" +
	"\x10supports_enforce\x18\x06 \x01(\bR\x0fsupportsEnforce\x12'\n" +
	"\x0fsupports_health\x18\a \x01(\bR\x0esupportsHealth\x12%\n" +
	"\x0ekernel_release\x18\b \x01(\tR\rkernelRelease\x12#\n" +
	"\rbtf_available\x18\t \x01(\bR\fbtfAvailable\x12'\n" +
	"\x0fbpffs_available\x18\n" +
	" \x01(\bR\x0ebpffsAvailable\"\x8f\x02\n" +
	"\x1cCollectionBehaviorCapability\x12\x1a\n" +
	"\bbehavior\x18\x01 \x01(\tR\bbehavior\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\x12-\n" +
	"\x12pushdown_selectors\x18\x03 \x03(\tR\x11pushdownSelectors\x120\n" +
	"\x14agent_side_selectors\x18\x04 \x03(\tR\x12agentSideSelectors\x123\n" +
	"\x15unsupported_selectors\x18\x05 \x03(\tR\x14unsupportedSelectors\x12%\n" +
	"\x0esensor_mapping\x18\x06 \x01(\tR\rsensorMapping\"\x9c\x03\n" +
	"\fSensorHealth\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x1c\n" +
	"\tinstalled\x18\x02 \x01(\bR\tinstalled\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12#\n" +
	"\rpolicy_loaded\x18\x05 \x01(\bR\fpolicyLoaded\x12\x1f\n" +
	"\vevents_seen\x18\x06 \x01(\x04R\n" +
	"eventsSeen\x12%\n" +
	"\x0eevents_dropped\x18\a \x01(\x04R\reventsDropped\x12!\n" +
	"\fparse_errors\x18\b \x01(\x04R\vparseErrors\x12#\n" +
	"\rrestart_count\x18\t \x01(\x04R\frestartCount\x12\"\n" +
	"\rlast_event_at\x18\n" +
	" \x01(\tR\vlastEventAt\x12(\n" +
	"\x10last_exit_reason\x18\v \x01(\tR\x0elastExitReason\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\"\x90\x02\n" +
	"\vQueueHealth\x12%\n" +
	"\x0equeued_batches\x18\x01 \x01(\rR\rqueuedBatches\x12!\n" +
	"\fqueued_bytes\x18\x02 \x01(\x03R\vqueuedBytes\x12\x1b\n" +
	"\tmax_bytes\x18\x03 \x01(\x03R\bmaxBytes\x12-\n" +
	"\x12backpressure_count\x18\x04 \x01(\x04R\x11backpressureCount\x12'\n" +
	"\x0fdropped_batches\x18\x05 \x01(\x04R\x0edroppedBatches\x12#\n" +
	"\rdropped_bytes\x18\x06 \x01(\x04R\fdroppedBytes\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\"\xae\x01\n" +
	"\fUploadHealth\x12)\n" +
	"\x10uploaded_batches\x18\x01 \x01(\rR\x0fuploadedBatches\x12+\n" +
	"\x11remaining_batches\x18\x02 \x01(\rR\x10remainingBatches\x12'\n" +
	"\x0fremaining_bytes\x18\x03 \x01(\x03R\x0eremainingBytes\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"\x92\x02\n" +
	"\tCEPHealth\x12#\n" +
	"\ractive_groups\x18\x01 \x01(\x04R\factiveGroups\x12%\n" +
	"\x0eevicted_groups\x18\x02 \x01(\x04R\revictedGroups\x12%\n" +
	"\x0eexpired_groups\x18\x03 \x01(\x04R\rexpiredGroups\x12,\n" +
	"\x12dropped_event_refs\x18\x04 \x01(\x04R\x10droppedEventRefs\x12\x1f\n" +
	"\veval_errors\x18\x05 \x01(\x04R\n" +
	"evalErrors\x12'\n" +
	"\x0femitted_signals\x18\x06 \x01(\x04R\x0eemittedSignals\x12\x1a\n" +
	"\bdegraded\x18\a \x01(\bR\bdegraded\"N\n" +
	"\rHealthRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.sysarmor.control.v1.RequestContextR\acontext\"\xff\x04\n" +
	"\x0eHealthResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x120\n" +
	"\x05scope\x18\x04 \x01(\v2\x1a.sysarmor.control.v1.ScopeR\x05scope\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tpolicy_id\x18\x06 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\a \x01(\x04R\rpolicyVersion\x12\x1f\n" +
	"\vpolicy_mode\x18\b \x01(\tR\n" +
	"policyMode\x12%\n" +
	"\x0euptime_seconds\x18\t \x01(\x03R\ruptimeSeconds\x12E\n" +
	"\n" +
	"capability\x18\n" +
	" \x01(\v2%.sysarmor.control.v1.SensorCapabilityR\n" +
	"capability\x129\n" +
	"\x06sensor\x18\v \x01(\v2!.sysarmor.control.v1.SensorHealthR\x06sensor\x126\n" +
	"\x05queue\x18\f \x01(\v2 .sysarmor.control.v1.QueueHealthR\x05queue\x129\n" +
	"\x06upload\x18\r \x01(\v2!.sysarmor.control.v1.UploadHealthR\x06upload\x12\x1f\n" +
	"\vobserved_at\x18\x0e \x01(\tR\n" +
	"observedAt\x120\n" +
	"\x03cep\x18\x0f \x01(\v2\x1e.sysarmor.control.v1.CEPHealthR\x03cep\"R\n" +
	"\x11CapabilityRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.sysarmor.control.v1.RequestContextR\acontext\"\xbc\x03\n" +
	"\x12CapabilityResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x120\n" +
	"\x05scope\x18\x04 \x01(\v2\x1a.sysarmor.control.v1.ScopeR\x05scope\x12=\n" +
	"\x06sensor\x18\x05 \x01(\v2%.sysarmor.control.v1.SensorCapabilityR\x06sensor\x12:\n" +
	"\x19supported_policy_sections\x18\x06 \x03(\tR\x17supportedPolicySections\x12<\n" +
	"\x1asupported_response_actions\x18\b \x03(\tR\x18supportedResponseActions\x12d\n" +
	"\x14collection_behaviors\x18\t \x03(\v21.sysarmor.control.v1.CollectionBehaviorCapabilityR\x13collectionBehaviorsJ\x04\b\a\x10\b\"U\n" +
	"\x14CurrentPolicyRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.sysarmor.control.v1.RequestContextR\acontext\"\xb2\x02\n" +
	"\x15CurrentPolicyResponse\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x120\n" +
	"\x05scope\x18\x04 \x01(\v2\x1a.sysarmor.control.v1.ScopeR\x05scope\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12%\n" +
	"\x0eendpoint_rules\x18\x06 \x03(\tR\rendpointRules\x12\x1f\n" +
	"\vcloud_rules\x18\a \x03(\tR\n" +
	"cloudRules\x12\x1c\n" +
	"\tpublished\x18\b \x01(\bR\tpublished\x12\x19\n" +
	"\braw_json\x18\t \x01(\tR\arawJson\"\xae\x01\n" +
	"\x12ApplyPolicyRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.sysarmor.control.v1.RequestContextR\acontext\x12\x1f\n" +
	"\vpolicy_type\x18\x02 \x01(\tR\n" +
	"policyType\x12\x1f\n" +
	"\vpolicy_json\x18\x03 \x01(\tR\n" +
	"policyJson\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\"\xb7\x01\n" +
	"\x13ApplyContentRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.sysarmor.control.v1.RequestContextR\acontext\x12!\n" +
	"\fcontent_json\x18\x02 \x01(\tR\vcontentJson\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\x12%\n" +
	"\x0eallow_unsigned\x18\x04 \x01(\bR\rallowUnsigned\"\xb2\x01\n" +
	"\rContentRecord\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\x12\x16\n" +
	"\x06signed\x18\x05 \x01(\bR\x06signed\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x19\n" +
	"\braw_json\x18\a \x01(\tR\arawJson\"g\n" +
	"\x12ListContentRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.sysarmor.control.v1.RequestContextR\acontext\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"S\n" +
	"\x13ListContentResponse\x12<\n" +
	"\arecords\x18\x01 \x03(\v2\".sysarmor.control.v1.ContentRecordR\arecords\"d\n" +
	"\x11GetContentRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.sysarmor.control.v1.RequestContextR\acontext\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\"P\n" +
	"\x12ContentGetResponse\x12:\n" +
	"\x06record\x18\x01 \x01(\v2\".sysarmor.control.v1.ContentRecordR\x06record\"\xbc\x01\n" +
	"\x0eAppliedSection\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12)\n" +
	"\x10requires_restart\x18\x04 \x01(\bR\x0frequiresRestart\x12\x18\n" +
	"\adetails\x18\x05 \x03(\tR\adetails\x12\x1f\n" +
	"\vreport_json\x18\x06 \x01(\tR\n" +
	"reportJson\"\xd5\x02\n" +
	"\n" +
	"ControlAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1b\n" +
	"\tpolicy_id\x18\x06 \x01(\tR\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\a \x01(\x04R\rpolicyVersion\x12?\n" +
	"\bsections\x18\b \x03(\v2#.sysarmor.control.v1.AppliedSectionR\bsections\x12\x18\n" +
	"\adetails\x18\t \x03(\tR\adetails\x12\x1f\n" +
	"\vreport_json\x18\n" +
	" \x01(\tR\n" +
	"reportJson\"\xd1\x01\n" +
	"\x12WatchEventsRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.sysarmor.control.v1.RequestContextR\acontext\x12\x1a\n" +
	"\bbehavior\x18\x02 \x01(\tR\bbehavior\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12%\n" +
	"\x0einclude_recent\x18\x04 \x01(\bR\rincludeRecent\x12#\n" +
	"\rsnapshot_only\x18\x05 \x01(\bR\fsnapshotOnly\"k\n" +
	"\x0fGetEventRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.sysarmor.control.v1.RequestContextR\acontext\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"I\n" +
	"\x10EventGetResponse\x125\n" +
	"\x05frame\x18\x01 \x01(\v2\x1f.sysarmor.control.v1.EventFrameR\x05frame\"\xba\x01\n" +
	"\n" +
	"EventFrame\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x1f\n" +
	"\vobserved_at\x18\x04 \x01(\tR\n" +
	"observedAt\x127\n" +
	"\x05event\x18\x05 \x01(\v2!.sysarmor.event.v1.CanonicalEventR\x05event\"\xe5\x01\n" +
	"\x13WatchSignalsRequest\x12=\n" +
	"\acontext\x18\x01 \x01(\v2#.sysarmor.control.v1.RequestContextR\acontext\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x14\n" +
	"\x05where\x18\x03 \x01(\tR\x05where\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12%\n" +
	"\x0einclude_recent\x18\x05 \x01(\bR\rincludeRecent\x12#\n" +
	"\rsnapshot_only\x18\x06 \x01(\bR\fsnapshotOnly\"\xb6\x01\n" +
	"\vSignalFrame\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x1f\n" +
	"\vobserved_at\x18\x04 \x01(\tR\n" +
	"observedAt\x122\n" +
	"\x06signal\x18\x05 \x01(\v2\x1a.sysarmor.signal.v1.SignalR\x06signal2\xb6\a\n" +
	"\x13AgentControlService\x12Q\n" +
	"\x06Health\x12\".sysarmor.control.v1.HealthRequest\x1a#.sysarmor.control.v1.HealthResponse\x12]\n" +
	"\n" +
	"Capability\x12&.sysarmor.control.v1.CapabilityRequest\x1a'.sysarmor.control.v1.CapabilityResponse\x12f\n" +
	"\rCurrentPolicy\x12).sysarmor.control.v1.CurrentPolicyRequest\x1a*.sysarmor.control.v1.CurrentPolicyResponse\x12W\n" +
	"\vApplyPolicy\x12'.sysarmor.control.v1.ApplyPolicyRequest\x1a\x1f.sysarmor.control.v1.ControlAck\x12Y\n" +
	"\fApplyContent\x12(.sysarmor.control.v1.ApplyContentRequest\x1a\x1f.sysarmor.control.v1.ControlAck\x12`\n" +
	"\vListContent\x12'.sysarmor.control.v1.ListContentRequest\x1a(.sysarmor.control.v1.ListContentResponse\x12]\n" +
	"\n" +
	"GetContent\x12&.sysarmor.control.v1.GetContentRequest\x1a'.sysarmor.control.v1.ContentGetResponse\x12W\n" +
	"\bGetEvent\x12$.sysarmor.control.v1.GetEventRequest\x1a%.sysarmor.control.v1.EventGetResponse\x12Y\n" +
	"\vWatchEvents\x12'.sysarmor.control.v1.WatchEventsRequest\x1a\x1f.sysarmor.control.v1.EventFrame0\x01\x12\\\n" +
	"\fWatchSignals\x12(.sysarmor.control.v1.WatchSignalsRequest\x1a .sysarmor.control.v1.SignalFrame0\x01BJZHgithub.com/sysarmor/sysarmor-next-project/api/proto/control/v1;controlv1b\x06proto3"

var (
	file_api_proto_control_v1_agentcontrol_proto_rawDescOnce sync.Once
	file_api_proto_control_v1_agentcontrol_proto_rawDescData []byte
)

func file_api_proto_control_v1_agentcontrol_proto_rawDescGZIP() []byte {
	file_api_proto_control_v1_agentcontrol_proto_rawDescOnce.Do(func() {
		file_api_proto_control_v1_agentcontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_control_v1_agentcontrol_proto_rawDesc), len(file_api_proto_control_v1_agentcontrol_proto_rawDesc)))
	})
	return file_api_proto_control_v1_agentcontrol_proto_rawDescData
}

var file_api_proto_control_v1_agentcontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_proto_control_v1_agentcontrol_proto_goTypes = []any{
	(*Scope)(nil),                        // 0: sysarmor.control.v1.Scope
	(*RequestContext)(nil),               // 1: sysarmor.control.v1.RequestContext
	(*SensorCapability)(nil),             // 2: sysarmor.control.v1.SensorCapability
	(*CollectionBehaviorCapability)(nil), // 3: sysarmor.control.v1.CollectionBehaviorCapability
	(*SensorHealth)(nil),                 // 4: sysarmor.control.v1.SensorHealth
	(*QueueHealth)(nil),                  // 5: sysarmor.control.v1.QueueHealth
	(*UploadHealth)(nil),                 // 6: sysarmor.control.v1.UploadHealth
	(*CEPHealth)(nil),                    // 7: sysarmor.control.v1.CEPHealth
	(*HealthRequest)(nil),                // 8: sysarmor.control.v1.HealthRequest
	(*HealthResponse)(nil),               // 9: sysarmor.control.v1.HealthResponse
	(*CapabilityRequest)(nil),            // 10: sysarmor.control.v1.CapabilityRequest
	(*CapabilityResponse)(nil),           // 11: sysarmor.control.v1.CapabilityResponse
	(*CurrentPolicyRequest)(nil),         // 12: sysarmor.control.v1.CurrentPolicyRequest
	(*CurrentPolicyResponse)(nil),        // 13: sysarmor.control.v1.CurrentPolicyResponse
	(*ApplyPolicyRequest)(nil),           // 14: sysarmor.control.v1.ApplyPolicyRequest
	(*ApplyContentRequest)(nil),          // 15: sysarmor.control.v1.ApplyContentRequest
	(*ContentRecord)(nil),                // 16: sysarmor.control.v1.ContentRecord
	(*ListContentRequest)(nil),           // 17: sysarmor.control.v1.ListContentRequest
	(*ListContentResponse)(nil),          // 18: sysarmor.control.v1.ListContentResponse
	(*GetContentRequest)(nil),            // 19: sysarmor.control.v1.GetContentRequest
	(*ContentGetResponse)(nil),           // 20: sysarmor.control.v1.ContentGetResponse
	(*AppliedSection)(nil),               // 21: sysarmor.control.v1.AppliedSection
	(*ControlAck)(nil),                   // 22: sysarmor.control.v1.ControlAck
	(*WatchEventsRequest)(nil),           // 23: sysarmor.control.v1.WatchEventsRequest
	(*GetEventRequest)(nil),              // 24: sysarmor.control.v1.GetEventRequest
	(*EventGetResponse)(nil),             // 25: sysarmor.control.v1.EventGetResponse
	(*EventFrame)(nil),                   // 26: sysarmor.control.v1.EventFrame
	(*WatchSignalsRequest)(nil),          // 27: sysarmor.control.v1.WatchSignalsRequest
	(*SignalFrame)(nil),                  // 28: sysarmor.control.v1.SignalFrame
	(*v1.CanonicalEvent)(nil),            // 29: sysarmor.event.v1.CanonicalEvent
	(*v11.Signal)(nil),                   // 30: sysarmor.signal.v1.Signal
}
var file_api_proto_control_v1_agentcontrol_proto_depIdxs = []int32{
	0,  // 0: sysarmor.control.v1.RequestContext.scope:type_name -> sysarmor.control.v1.Scope
	1,  // 1: sysarmor.control.v1.HealthRequest.context:type_name -> sysarmor.control.v1.RequestContext
	0,  // 2: sysarmor.control.v1.HealthResponse.scope:type_name -> sysarmor.control.v1.Scope
	2,  // 3: sysarmor.control.v1.HealthResponse.capability:type_name -> sysarmor.control.v1.SensorCapability
	4,  // 4: sysarmor.control.v1.HealthResponse.sensor:type_name -> sysarmor.control.v1.SensorHealth
	5,  // 5: sysarmor.control.v1.HealthResponse.queue:type_name -> sysarmor.control.v1.QueueHealth
	6,  // 6: sysarmor.control.v1.HealthResponse.upload:type_name -> sysarmor.control.v1.UploadHealth
	7,  // 7: sysarmor.control.v1.HealthResponse.cep:type_name -> sysarmor.control.v1.CEPHealth
	1,  // 8: sysarmor.control.v1.CapabilityRequest.context:type_name -> sysarmor.control.v1.RequestContext
	0,  // 9: sysarmor.control.v1.CapabilityResponse.scope:type_name -> sysarmor.control.v1.Scope
	2,  // 10: sysarmor.control.v1.CapabilityResponse.sensor:type_name -> sysarmor.control.v1.SensorCapability
	3,  // 11: sysarmor.control.v1.CapabilityResponse.collection_behaviors:type_name -> sysarmor.control.v1.CollectionBehaviorCapability
	1,  // 12: sysarmor.control.v1.CurrentPolicyRequest.context:type_name -> sysarmor.control.v1.RequestContext
	0,  // 13: sysarmor.control.v1.CurrentPolicyResponse.scope:type_name -> sysarmor.control.v1.Scope
	1,  // 14: sysarmor.control.v1.ApplyPolicyRequest.context:type_name -> sysarmor.control.v1.RequestContext
	1,  // 15: sysarmor.control.v1.ApplyContentRequest.context:type_name -> sysarmor.control.v1.RequestContext
	1,  // 16: sysarmor.control.v1.ListContentRequest.context:type_name -> sysarmor.control.v1.RequestContext
	16, // 17: sysarmor.control.v1.ListContentResponse.records:type_name -> sysarmor.control.v1.ContentRecord
	1,  // 18: sysarmor.control.v1.GetContentRequest.context:type_name -> sysarmor.control.v1.RequestContext
	16, // 19: sysarmor.control.v1.ContentGetResponse.record:type_name -> sysarmor.control.v1.ContentRecord
	21, // 20: sysarmor.control.v1.ControlAck.sections:type_name -> sysarmor.control.v1.AppliedSection
	1,  // 21: sysarmor.control.v1.WatchEventsRequest.context:type_name -> sysarmor.control.v1.RequestContext
	1,  // 22: sysarmor.control.v1.GetEventRequest.context:type_name -> sysarmor.control.v1.RequestContext
	26, // 23: sysarmor.control.v1.EventGetResponse.frame:type_name -> sysarmor.control.v1.EventFrame
	29, // 24: sysarmor.control.v1.EventFrame.event:type_name -> sysarmor.event.v1.CanonicalEvent
	1,  // 25: sysarmor.control.v1.WatchSignalsRequest.context:type_name -> sysarmor.control.v1.RequestContext
	30, // 26: sysarmor.control.v1.SignalFrame.signal:type_name -> sysarmor.signal.v1.Signal
	8,  // 27: sysarmor.control.v1.AgentControlService.Health:input_type -> sysarmor.control.v1.HealthRequest
	10, // 28: sysarmor.control.v1.AgentControlService.Capability:input_type -> sysarmor.control.v1.CapabilityRequest
	12, // 29: sysarmor.control.v1.AgentControlService.CurrentPolicy:input_type -> sysarmor.control.v1.CurrentPolicyRequest
	14, // 30: sysarmor.control.v1.AgentControlService.ApplyPolicy:input_type -> sysarmor.control.v1.ApplyPolicyRequest
	15, // 31: sysarmor.control.v1.AgentControlService.ApplyContent:input_type -> sysarmor.control.v1.ApplyContentRequest
	17, // 32: sysarmor.control.v1.AgentControlService.ListContent:input_type -> sysarmor.control.v1.ListContentRequest
	19, // 33: sysarmor.control.v1.AgentControlService.GetContent:input_type -> sysarmor.control.v1.GetContentRequest
	24, // 34: sysarmor.control.v1.AgentControlService.GetEvent:input_type -> sysarmor.control.v1.GetEventRequest
	23, // 35: sysarmor.control.v1.AgentControlService.WatchEvents:input_type -> sysarmor.control.v1.WatchEventsRequest
	27, // 36: sysarmor.control.v1.AgentControlService.WatchSignals:input_type -> sysarmor.control.v1.WatchSignalsRequest
	9,  // 37: sysarmor.control.v1.AgentControlService.Health:output_type -> sysarmor.control.v1.HealthResponse
	11, // 38: sysarmor.control.v1.AgentControlService.Capability:output_type -> sysarmor.control.v1.CapabilityResponse
	13, // 39: sysarmor.control.v1.AgentControlService.CurrentPolicy:output_type -> sysarmor.control.v1.CurrentPolicyResponse
	22, // 40: sysarmor.control.v1.AgentControlService.ApplyPolicy:output_type -> sysarmor.control.v1.ControlAck
	22, // 41: sysarmor.control.v1.AgentControlService.ApplyContent:output_type -> sysarmor.control.v1.ControlAck
	18, // 42: sysarmor.control.v1.AgentControlService.ListContent:output_type -> sysarmor.control.v1.ListContentResponse
	20, // 43: sysarmor.control.v1.AgentControlService.GetContent:output_type -> sysarmor.control.v1.ContentGetResponse
	25, // 44: sysarmor.control.v1.AgentControlService.GetEvent:output_type -> sysarmor.control.v1.EventGetResponse
	26, // 45: sysarmor.control.v1.AgentControlService.WatchEvents:output_type -> sysarmor.control.v1.EventFrame
	28, // 46: sysarmor.control.v1.AgentControlService.WatchSignals:output_type -> sysarmor.control.v1.SignalFrame
	37, // [37:47] is the sub-list for method output_type
	27, // [27:37] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_api_proto_control_v1_agentcontrol_proto_init() }
func file_api_proto_control_v1_agentcontrol_proto_init() {
	if File_api_proto_control_v1_agentcontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_control_v1_agentcontrol_proto_rawDesc), len(file_api_proto_control_v1_agentcontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_control_v1_agentcontrol_proto_goTypes,
		DependencyIndexes: file_api_proto_control_v1_agentcontrol_proto_depIdxs,
		MessageInfos:      file_api_proto_control_v1_agentcontrol_proto_msgTypes,
	}.Build()
	File_api_proto_control_v1_agentcontrol_proto = out.File
	file_api_proto_control_v1_agentcontrol_proto_goTypes = nil
	file_api_proto_control_v1_agentcontrol_proto_depIdxs = nil
}
