// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: api/proto/control/v1/agentcontrol.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentControlService_Health_FullMethodName        = "/sysarmor.control.v1.AgentControlService/Health"
	AgentControlService_Capability_FullMethodName    = "/sysarmor.control.v1.AgentControlService/Capability"
	AgentControlService_CurrentPolicy_FullMethodName = "/sysarmor.control.v1.AgentControlService/CurrentPolicy"
	AgentControlService_ApplyPolicy_FullMethodName   = "/sysarmor.control.v1.AgentControlService/ApplyPolicy"
	AgentControlService_ApplyContent_FullMethodName  = "/sysarmor.control.v1.AgentControlService/ApplyContent"
	AgentControlService_ListContent_FullMethodName   = "/sysarmor.control.v1.AgentControlService/ListContent"
	AgentControlService_GetContent_FullMethodName    = "/sysarmor.control.v1.AgentControlService/GetContent"
	AgentControlService_GetEvent_FullMethodName      = "/sysarmor.control.v1.AgentControlService/GetEvent"
	AgentControlService_WatchEvents_FullMethodName   = "/sysarmor.control.v1.AgentControlService/WatchEvents"
	AgentControlService_WatchSignals_FullMethodName  = "/sysarmor.control.v1.AgentControlService/WatchSignals"
)

// AgentControlServiceClient is the client API for AgentControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentControlServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Capability(ctx context.Context, in *CapabilityRequest, opts ...grpc.CallOption) (*CapabilityResponse, error)
	CurrentPolicy(ctx context.Context, in *CurrentPolicyRequest, opts ...grpc.CallOption) (*CurrentPolicyResponse, error)
	ApplyPolicy(ctx context.Context, in *ApplyPolicyRequest, opts ...grpc.CallOption) (*ControlAck, error)
	ApplyContent(ctx context.Context, in *ApplyContentRequest, opts ...grpc.CallOption) (*ControlAck, error)
	ListContent(ctx context.Context, in *ListContentRequest, opts ...grpc.CallOption) (*ListContentResponse, error)
	GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*ContentGetResponse, error)
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*EventGetResponse, error)
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventFrame], error)
	WatchSignals(ctx context.Context, in *WatchSignalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignalFrame], error)
}

type agentControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlServiceClient(cc grpc.ClientConnInterface) AgentControlServiceClient {
	return &agentControlServiceClient{cc}
}

func (c *agentControlServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AgentControlService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlServiceClient) Capability(ctx context.Context, in *CapabilityRequest, opts ...grpc.CallOption) (*CapabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilityResponse)
	err := c.cc.Invoke(ctx, AgentControlService_Capability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlServiceClient) CurrentPolicy(ctx context.Context, in *CurrentPolicyRequest, opts ...grpc.CallOption) (*CurrentPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrentPolicyResponse)
	err := c.cc.Invoke(ctx, AgentControlService_CurrentPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlServiceClient) ApplyPolicy(ctx context.Context, in *ApplyPolicyRequest, opts ...grpc.CallOption) (*ControlAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlAck)
	err := c.cc.Invoke(ctx, AgentControlService_ApplyPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlServiceClient) ApplyContent(ctx context.Context, in *ApplyContentRequest, opts ...grpc.CallOption) (*ControlAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlAck)
	err := c.cc.Invoke(ctx, AgentControlService_ApplyContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlServiceClient) ListContent(ctx context.Context, in *ListContentRequest, opts ...grpc.CallOption) (*ListContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentResponse)
	err := c.cc.Invoke(ctx, AgentControlService_ListContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlServiceClient) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*ContentGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentGetResponse)
	err := c.cc.Invoke(ctx, AgentControlService_GetContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlServiceClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*EventGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventGetResponse)
	err := c.cc.Invoke(ctx, AgentControlService_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlServiceClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControlService_ServiceDesc.Streams[0], AgentControlService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, EventFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlService_WatchEventsClient = grpc.ServerStreamingClient[EventFrame]

func (c *agentControlServiceClient) WatchSignals(ctx context.Context, in *WatchSignalsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignalFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControlService_ServiceDesc.Streams[1], AgentControlService_WatchSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchSignalsRequest, SignalFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlService_WatchSignalsClient = grpc.ServerStreamingClient[SignalFrame]

// AgentControlServiceServer is the server API for AgentControlService service.
// All implementations must embed UnimplementedAgentControlServiceServer
// for forward compatibility.
type AgentControlServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Capability(context.Context, *CapabilityRequest) (*CapabilityResponse, error)
	CurrentPolicy(context.Context, *CurrentPolicyRequest) (*CurrentPolicyResponse, error)
	ApplyPolicy(context.Context, *ApplyPolicyRequest) (*ControlAck, error)
	ApplyContent(context.Context, *ApplyContentRequest) (*ControlAck, error)
	ListContent(context.Context, *ListContentRequest) (*ListContentResponse, error)
	GetContent(context.Context, *GetContentRequest) (*ContentGetResponse, error)
	GetEvent(context.Context, *GetEventRequest) (*EventGetResponse, error)
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[EventFrame]) error
	WatchSignals(*WatchSignalsRequest, grpc.ServerStreamingServer[SignalFrame]) error
	mustEmbedUnimplementedAgentControlServiceServer()
}

// UnimplementedAgentControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServiceServer struct{}

func (UnimplementedAgentControlServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAgentControlServiceServer) Capability(context.Context, *CapabilityRequest) (*CapabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capability not implemented")
}
func (UnimplementedAgentControlServiceServer) CurrentPolicy(context.Context, *CurrentPolicyRequest) (*CurrentPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CurrentPolicy not implemented")
}
func (UnimplementedAgentControlServiceServer) ApplyPolicy(context.Context, *ApplyPolicyRequest) (*ControlAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPolicy not implemented")
}
func (UnimplementedAgentControlServiceServer) ApplyContent(context.Context, *ApplyContentRequest) (*ControlAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyContent not implemented")
}
func (UnimplementedAgentControlServiceServer) ListContent(context.Context, *ListContentRequest) (*ListContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContent not implemented")
}
func (UnimplementedAgentControlServiceServer) GetContent(context.Context, *GetContentRequest) (*ContentGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContent not implemented")
}
func (UnimplementedAgentControlServiceServer) GetEvent(context.Context, *GetEventRequest) (*EventGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedAgentControlServiceServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[EventFrame]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedAgentControlServiceServer) WatchSignals(*WatchSignalsRequest, grpc.ServerStreamingServer[SignalFrame]) error {
	return status.Error(codes.Unimplemented, "method WatchSignals not implemented")
}
func (UnimplementedAgentControlServiceServer) mustEmbedUnimplementedAgentControlServiceServer() {}
func (UnimplementedAgentControlServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServiceServer will
// result in compilation errors.
type UnsafeAgentControlServiceServer interface {
	mustEmbedUnimplementedAgentControlServiceServer()
}

func RegisterAgentControlServiceServer(s grpc.ServiceRegistrar, srv AgentControlServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControlService_ServiceDesc, srv)
}

func _AgentControlService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlService_Capability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServiceServer).Capability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlService_Capability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServiceServer).Capability(ctx, req.(*CapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlService_CurrentPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServiceServer).CurrentPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlService_CurrentPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServiceServer).CurrentPolicy(ctx, req.(*CurrentPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlService_ApplyPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServiceServer).ApplyPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlService_ApplyPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServiceServer).ApplyPolicy(ctx, req.(*ApplyPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlService_ApplyContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServiceServer).ApplyContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlService_ApplyContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServiceServer).ApplyContent(ctx, req.(*ApplyContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlService_ListContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServiceServer).ListContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlService_ListContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServiceServer).ListContent(ctx, req.(*ListContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlService_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServiceServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlService_GetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServiceServer).GetContent(ctx, req.(*GetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServiceServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentControlServiceServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, EventFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlService_WatchEventsServer = grpc.ServerStreamingServer[EventFrame]

func _AgentControlService_WatchSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchSignalsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentControlServiceServer).WatchSignals(m, &grpc.GenericServerStream[WatchSignalsRequest, SignalFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlService_WatchSignalsServer = grpc.ServerStreamingServer[SignalFrame]

// AgentControlService_ServiceDesc is the grpc.ServiceDesc for AgentControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysarmor.control.v1.AgentControlService",
	HandlerType: (*AgentControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AgentControlService_Health_Handler,
		},
		{
			MethodName: "Capability",
			Handler:    _AgentControlService_Capability_Handler,
		},
		{
			MethodName: "CurrentPolicy",
			Handler:    _AgentControlService_CurrentPolicy_Handler,
		},
		{
			MethodName: "ApplyPolicy",
			Handler:    _AgentControlService_ApplyPolicy_Handler,
		},
		{
			MethodName: "ApplyContent",
			Handler:    _AgentControlService_ApplyContent_Handler,
		},
		{
			MethodName: "ListContent",
			Handler:    _AgentControlService_ListContent_Handler,
		},
		{
			MethodName: "GetContent",
			Handler:    _AgentControlService_GetContent_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _AgentControlService_GetEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _AgentControlService_WatchEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchSignals",
			Handler:       _AgentControlService_WatchSignals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/control/v1/agentcontrol.proto",
}
