#!/usr/bin/env bash
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
workflow="$REPO/.github/workflows/dev-prerelease.yml"
dependabot="$REPO/.github/dependabot.yml"

test -f "$workflow"
grep -Fq 'workflow_dispatch:' "$workflow"
grep -Fq 'github.ref != '\''refs/heads/dev'\''' "$workflow"
grep -Fq 'go test ./...' "$workflow"
grep -Fq 'container-entrypoint.sh' "$workflow"
grep -Fq 'suites/product/endpoint/release-container-e2e-contract.sh' "$workflow"
grep -Fq -- '--tetragon-mode download' "$workflow"
grep -Fq 'build-github-assets.sh' "$workflow"
grep -Fq 'actions/attest-build-provenance@' "$workflow"
grep -Fq 'actions/upload-artifact@' "$workflow"
grep -Fq 'actions/download-artifact@' "$workflow"
grep -Fq 'contents: read' "$workflow"
grep -Fq 'contents: write' "$workflow"
grep -Fq -- '--prerelease' "$workflow"
grep -Fq -- '--target "$GITHUB_SHA"' "$workflow"
grep -Fq -- '--profile linux-container' "$workflow"
grep -Fq 'util-linux' "$workflow"
grep -Fq '/usr/local/bin/sysarmor-container-entrypoint' "$workflow"
grep -Fq 'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1' "$workflow"
grep -Fq 'actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0' "$workflow"
grep -Fq 'actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1' "$workflow"
grep -Fq 'actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1' "$workflow"
grep -Fq 'actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1' "$workflow"

test -f "$dependabot"
grep -Fq 'package-ecosystem: github-actions' "$dependabot"
grep -Fq 'target-branch: dev' "$dependabot"
grep -Fq 'interval: weekly' "$dependabot"

echo "[dev-prerelease-workflow] ok"
