// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/signal/v1/signal.proto

package signalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalWhere int32

const (
	SignalWhere_SIGNAL_WHERE_UNSPECIFIED SignalWhere = 0
	SignalWhere_SIGNAL_WHERE_ENDPOINT    SignalWhere = 1
	SignalWhere_SIGNAL_WHERE_CLOUD       SignalWhere = 2
)

// Enum value maps for SignalWhere.
var (
	SignalWhere_name = map[int32]string{
		0: "SIGNAL_WHERE_UNSPECIFIED",
		1: "SIGNAL_WHERE_ENDPOINT",
		2: "SIGNAL_WHERE_CLOUD",
	}
	SignalWhere_value = map[string]int32{
		"SIGNAL_WHERE_UNSPECIFIED": 0,
		"SIGNAL_WHERE_ENDPOINT":    1,
		"SIGNAL_WHERE_CLOUD":       2,
	}
)

func (x SignalWhere) Enum() *SignalWhere {
	p := new(SignalWhere)
	*p = x
	return p
}

func (x SignalWhere) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalWhere) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_signal_v1_signal_proto_enumTypes[0].Descriptor()
}

func (SignalWhere) Type() protoreflect.EnumType {
	return &file_api_proto_signal_v1_signal_proto_enumTypes[0]
}

func (x SignalWhere) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalWhere.Descriptor instead.
func (SignalWhere) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_signal_v1_signal_proto_rawDescGZIP(), []int{0}
}

type EntityRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRef) Reset() {
	*x = EntityRef{}
	mi := &file_api_proto_signal_v1_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRef) ProtoMessage() {}

func (x *EntityRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_v1_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRef.ProtoReflect.Descriptor instead.
func (*EntityRef) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_v1_signal_proto_rawDescGZIP(), []int{0}
}

func (x *EntityRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EntityRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EntityRef) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type EvidenceBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventRefs     []string               `protobuf:"bytes,2,rep,name=event_refs,json=eventRefs,proto3" json:"event_refs,omitempty"`
	RawRefs       []string               `protobuf:"bytes,3,rep,name=raw_refs,json=rawRefs,proto3" json:"raw_refs,omitempty"`
	Entities      []*EntityRef           `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceBundle) Reset() {
	*x = EvidenceBundle{}
	mi := &file_api_proto_signal_v1_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceBundle) ProtoMessage() {}

func (x *EvidenceBundle) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_v1_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceBundle.ProtoReflect.Descriptor instead.
func (*EvidenceBundle) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_v1_signal_proto_rawDescGZIP(), []int{1}
}

func (x *EvidenceBundle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EvidenceBundle) GetEventRefs() []string {
	if x != nil {
		return x.EventRefs
	}
	return nil
}

func (x *EvidenceBundle) GetRawRefs() []string {
	if x != nil {
		return x.RawRefs
	}
	return nil
}

func (x *EvidenceBundle) GetEntities() []*EntityRef {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *EvidenceBundle) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ResponseIntent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResponseIntent    string                 `protobuf:"bytes,1,opt,name=response_intent,json=responseIntent,proto3" json:"response_intent,omitempty"`
	RecommendedAction string                 `protobuf:"bytes,2,opt,name=recommended_action,json=recommendedAction,proto3" json:"recommended_action,omitempty"`
	Confidence        uint32                 `protobuf:"varint,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reason            string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResponseIntent) Reset() {
	*x = ResponseIntent{}
	mi := &file_api_proto_signal_v1_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseIntent) ProtoMessage() {}

func (x *ResponseIntent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_v1_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseIntent.ProtoReflect.Descriptor instead.
func (*ResponseIntent) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_v1_signal_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseIntent) GetResponseIntent() string {
	if x != nil {
		return x.ResponseIntent
	}
	return ""
}

func (x *ResponseIntent) GetRecommendedAction() string {
	if x != nil {
		return x.RecommendedAction
	}
	return ""
}

func (x *ResponseIntent) GetConfidence() uint32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ResponseIntent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Signal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Where          SignalWhere            `protobuf:"varint,3,opt,name=where,proto3,enum=sysarmor.signal.v1.SignalWhere" json:"where,omitempty"`
	BaseRisk       uint32                 `protobuf:"varint,4,opt,name=base_risk,json=baseRisk,proto3" json:"base_risk,omitempty"`
	LocalRarity    float32                `protobuf:"fixed32,5,opt,name=local_rarity,json=localRarity,proto3" json:"local_rarity,omitempty"`
	GlobalRarity   float32                `protobuf:"fixed32,6,opt,name=global_rarity,json=globalRarity,proto3" json:"global_rarity,omitempty"`
	LineageId      string                 `protobuf:"bytes,7,opt,name=lineage_id,json=lineageId,proto3" json:"lineage_id,omitempty"`
	Entities       []*EntityRef           `protobuf:"bytes,8,rep,name=entities,proto3" json:"entities,omitempty"`
	EventRefs      []string               `protobuf:"bytes,9,rep,name=event_refs,json=eventRefs,proto3" json:"event_refs,omitempty"`
	SignalRefs     []string               `protobuf:"bytes,10,rep,name=signal_refs,json=signalRefs,proto3" json:"signal_refs,omitempty"`
	Terminal       bool                   `protobuf:"varint,11,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Evidence       *EvidenceBundle        `protobuf:"bytes,12,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Scenario       string                 `protobuf:"bytes,13,opt,name=scenario,proto3" json:"scenario,omitempty"`
	CrossLineage   bool                   `protobuf:"varint,14,opt,name=cross_lineage,json=crossLineage,proto3" json:"cross_lineage,omitempty"`
	ResponseIntent *ResponseIntent        `protobuf:"bytes,15,opt,name=response_intent,json=responseIntent,proto3" json:"response_intent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_api_proto_signal_v1_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_signal_v1_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_api_proto_signal_v1_signal_proto_rawDescGZIP(), []int{3}
}

func (x *Signal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Signal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Signal) GetWhere() SignalWhere {
	if x != nil {
		return x.Where
	}
	return SignalWhere_SIGNAL_WHERE_UNSPECIFIED
}

func (x *Signal) GetBaseRisk() uint32 {
	if x != nil {
		return x.BaseRisk
	}
	return 0
}

func (x *Signal) GetLocalRarity() float32 {
	if x != nil {
		return x.LocalRarity
	}
	return 0
}

func (x *Signal) GetGlobalRarity() float32 {
	if x != nil {
		return x.GlobalRarity
	}
	return 0
}

func (x *Signal) GetLineageId() string {
	if x != nil {
		return x.LineageId
	}
	return ""
}

func (x *Signal) GetEntities() []*EntityRef {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Signal) GetEventRefs() []string {
	if x != nil {
		return x.EventRefs
	}
	return nil
}

func (x *Signal) GetSignalRefs() []string {
	if x != nil {
		return x.SignalRefs
	}
	return nil
}

func (x *Signal) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *Signal) GetEvidence() *EvidenceBundle {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Signal) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *Signal) GetCrossLineage() bool {
	if x != nil {
		return x.CrossLineage
	}
	return false
}

func (x *Signal) GetResponseIntent() *ResponseIntent {
	if x != nil {
		return x.ResponseIntent
	}
	return nil
}

var File_api_proto_signal_v1_signal_proto protoreflect.FileDescriptor

const file_api_proto_signal_v1_signal_proto_rawDesc = "" +
	"\n" +
	" api/proto/signal/v1/signal.proto\x12\x12sysarmor.signal.v1\"E\n" +
	"\tEntityRef\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\xaf\x01\n" +
	"\x0eEvidenceBundle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_refs\x18\x02 \x03(\tR\teventRefs\x12\x19\n" +
	"\braw_refs\x18\x03 \x03(\tR\arawRefs\x129\n" +
	"\bentities\x18\x04 \x03(\v2\x1d.sysarmor.signal.v1.EntityRefR\bentities\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\"\xa0\x01\n" +
	"\x0eResponseIntent\x12'\n" +
	"\x0fresponse_intent\x18\x01 \x01(\tR\x0eresponseIntent\x12-\n" +
	"\x12recommended_action\x18\x02 \x01(\tR\x11recommendedAction\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\rR\n" +
	"confidence\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xcc\x04\n" +
	"\x06Signal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\x05where\x18\x03 \x01(\x0e2\x1f.sysarmor.signal.v1.SignalWhereR\x05where\x12\x1b\n" +
	"\tbase_risk\x18\x04 \x01(\rR\bbaseRisk\x12!\n" +
	"\flocal_rarity\x18\x05 \x01(\x02R\vlocalRarity\x12#\n" +
	"\rglobal_rarity\x18\x06 \x01(\x02R\fglobalRarity\x12\x1d\n" +
	"\n" +
	"lineage_id\x18\a \x01(\tR\tlineageId\x129\n" +
	"\bentities\x18\b \x03(\v2\x1d.sysarmor.signal.v1.EntityRefR\bentities\x12\x1d\n" +
	"\n" +
	"event_refs\x18\t \x03(\tR\teventRefs\x12\x1f\n" +
	"\vsignal_refs\x18\n" +
	" \x03(\tR\n" +
	"signalRefs\x12\x1a\n" +
	"\bterminal\x18\v \x01(\bR\bterminal\x12>\n" +
	"\bevidence\x18\f \x01(\v2\".sysarmor.signal.v1.EvidenceBundleR\bevidence\x12\x1a\n" +
	"\bscenario\x18\r \x01(\tR\bscenario\x12#\n" +
	"\rcross_lineage\x18\x0e \x01(\bR\fcrossLineage\x12K\n" +
	"\x0fresponse_intent\x18\x0f \x01(\v2\".sysarmor.signal.v1.ResponseIntentR\x0eresponseIntent*^\n" +
	"\vSignalWhere\x12\x1c\n" +
	"\x18SIGNAL_WHERE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SIGNAL_WHERE_ENDPOINT\x10\x01\x12\x16\n" +
	"\x12SIGNAL_WHERE_CLOUD\x10\x02BHZFgithub.com/sysarmor/sysarmor-next-project/api/proto/signal/v1;signalv1b\x06proto3"

var (
	file_api_proto_signal_v1_signal_proto_rawDescOnce sync.Once
	file_api_proto_signal_v1_signal_proto_rawDescData []byte
)

func file_api_proto_signal_v1_signal_proto_rawDescGZIP() []byte {
	file_api_proto_signal_v1_signal_proto_rawDescOnce.Do(func() {
		file_api_proto_signal_v1_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_signal_v1_signal_proto_rawDesc), len(file_api_proto_signal_v1_signal_proto_rawDesc)))
	})
	return file_api_proto_signal_v1_signal_proto_rawDescData
}

var file_api_proto_signal_v1_signal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_signal_v1_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_signal_v1_signal_proto_goTypes = []any{
	(SignalWhere)(0),       // 0: sysarmor.signal.v1.SignalWhere
	(*EntityRef)(nil),      // 1: sysarmor.signal.v1.EntityRef
	(*EvidenceBundle)(nil), // 2: sysarmor.signal.v1.EvidenceBundle
	(*ResponseIntent)(nil), // 3: sysarmor.signal.v1.ResponseIntent
	(*Signal)(nil),         // 4: sysarmor.signal.v1.Signal
}
var file_api_proto_signal_v1_signal_proto_depIdxs = []int32{
	1, // 0: sysarmor.signal.v1.EvidenceBundle.entities:type_name -> sysarmor.signal.v1.EntityRef
	0, // 1: sysarmor.signal.v1.Signal.where:type_name -> sysarmor.signal.v1.SignalWhere
	1, // 2: sysarmor.signal.v1.Signal.entities:type_name -> sysarmor.signal.v1.EntityRef
	2, // 3: sysarmor.signal.v1.Signal.evidence:type_name -> sysarmor.signal.v1.EvidenceBundle
	3, // 4: sysarmor.signal.v1.Signal.response_intent:type_name -> sysarmor.signal.v1.ResponseIntent
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_signal_v1_signal_proto_init() }
func file_api_proto_signal_v1_signal_proto_init() {
	if File_api_proto_signal_v1_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_signal_v1_signal_proto_rawDesc), len(file_api_proto_signal_v1_signal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_signal_v1_signal_proto_goTypes,
		DependencyIndexes: file_api_proto_signal_v1_signal_proto_depIdxs,
		EnumInfos:         file_api_proto_signal_v1_signal_proto_enumTypes,
		MessageInfos:      file_api_proto_signal_v1_signal_proto_msgTypes,
	}.Build()
	File_api_proto_signal_v1_signal_proto = out.File
	file_api_proto_signal_v1_signal_proto_goTypes = nil
	file_api_proto_signal_v1_signal_proto_depIdxs = nil
}
